pluralsight/pando

website/src/components/LiveExampleTabs/LiveExampleTabs.js
website/src/components/LiveExampleTabs/LiveExampleTabs.module.css

Live examples tabs where using all default "codesandbox" icon.
Adds chakra & mui icons to tabs. SC uses an emoji which looks weird so we will probably keep it the codesandbox one.

docs: add framework icons to LiveExamplesTabs

---

packages/headless-styles/src/components/Button/buttonCSS.module.css

Chakra styles had incorrect size for "medium" in Button CSS
Updates styles to use correct height.

fix(hs): add correct height to base chakra class in Button

---

website/docusaurus.config.js

Analytics tracking but not actually sending "hits"
Changed the ID to use the "measurement id" which is diff from docusaurus docs.

docs: update gtag to use measurement ID vs. stream ID

---

packages/headless-styles/src/components/Badge/badgeJS.ts

MUI - Badge extra padding declaration in `muiLabelOverride` was overriding our inline-padding props.
Removes it which allows the padding to be correct (tested in browser from sandbox).

fix(hs): remove unnecessary padding prop in muiLabelOverride

---

packages/headless-styles/package.json

contributes to #200 
Imports are breaking apps that use older versions of Node (like our docs website) due to TS not fully supporting `.mjs` & `.cjs` extensions. Testing out if we can fix the error without doing too much surgery by just temporarily removing the `types` field until TS ships the [new feature](https://www.typescriptlang.org/docs/handbook/esm-node.html) which is [still buggy](https://github.com/microsoft/TypeScript/issues/46452)

fix(hs): temporarily remove type "module" in package.json

---

packages/headless-styles/src/components/Progress/progressJS.ts
packages/headless-styles/src/index.ts

closes #219 
Adds `muiReset` for the LinearProgress component (in MUI)
**Reset vs. Override**
We are using the term "reset" here because we are literally resetting the styles on the MUI component itself. In the latter component (Badge) we are not resetting - we are overriding the styles of an internal element to the Badge.

feat(hs): add muiReset for Progress

---

packages/headless-styles/sandbox/src/components/Progress.jsx
packages/headless-styles/src/components/Progress/progressJS.ts
packages/headless-styles/src/index.ts
packages/headless-styles/tests/progress/progressJS.test.ts

closes #235 
* Updates Progress JS API to use correct `size` property key
* Exposes ProgressOptions type for users (since they will have to build their own components)

fix:  use correct size property for Progress JS

---

packages/headless-styles/package.json
packages/headless-styles/src/index.ts
packages/headless-styles/src/types.ts

Non-TS loaders are failing due to us exporting types in the main entry
Moves types exports to types.ts to prevent failures for non-TS environments

fix(hs): add types.ts for non-TS environments

---

packages/headless-styles/src/components/Icon/iconCSS.module.css
packages/headless-styles/src/components/Icon/iconCSS.ts
packages/headless-styles/tests/icon/iconCSS.test.ts

closes #254 
Icon size class names are the same as the ones used for some other components, creating a conflict when exporting classes for svelte
Icon classes are renamed to be specific to icons.

fix(headless-styles): rename icon size classes

---

packages/headless-styles/src/components/Button/buttonCSS.ts
packages/headless-styles/tests/button/buttonCSS.test.ts

Contributes to #312 
Refactors Button prop getter to use getClassProp.
Also returns `type="button"` for Svelte, which was previously missing

refactor(headless-styles): use createClassProp for Button

---

packages/headless-styles/sandbox/src/components/IconButton.jsx
packages/headless-styles/src/components/Button/iconButtonCSS.ts
packages/headless-styles/src/components/Button/shared.ts

contributes to #172 
Cleans up iconButtonCSS to use same pattern as newer helpers.
@Rykus0 I'm comfortable with keeping the Icon Button logic in the Button directory and this API now that I've hammered it pretty hard in the sandbox. Go ahead and kill that other PR and add your JS API here.
We can and should still make the Icon Button a separate docs page though. 👍

refactor(hs): cleanup iconButtonCSS.ts

---

packages/headless-styles/src/components/Button/buttonCSS.module.css
packages/headless-styles/src/components/Button/iconButtonCSS.ts
packages/headless-styles/src/components/Button/shared.ts
packages/headless-styles/tests/button/iconButtonCSS.test.ts

contributes to #172 
Simplifies icon button classes.  Instead of using separate size classes for icon button, now use a single class and compose - this also more clearly ensures the base styles are overridden.
Adds a min-width for a slightly more robust sizing across all styles.
Includes `tech` in the returned iconOptions to simplify usage.

refactor(headless-styles): use simpler, more robust icon button styles

---

packages/headless-styles/sandbox/src/components/Alert.jsx
packages/headless-styles/src/components/Alert/alertCSS.module.css
packages/headless-styles/src/components/Alert/alertCSS.ts
packages/headless-styles/src/components/Alert/generated/alertCSS.module.ts
packages/headless-styles/tests/alert/alertCSS.test.ts

contributes #406 
Adds remaining kind styles to CSS module for Alert

feat(hs): add remaining kind styles to Alert CSS

---

packages/headless-styles/src/components/Tag/generated/tagCSS.module.ts
packages/headless-styles/src/components/Tag/tagCSS.module.css
packages/headless-styles/src/components/Tag/tagJS.ts

contributes to #426 
Base typography styles are being applied on hover, resulting in an underline.
Explicitly sets the `text-decoration` on hover to override any styles applied to the `a` tag
Next (and final) step is updating the HS dependency in the docs

fix(headless-styles): add base hover decoration for tag

---

packages/headless-styles/src/components/Menu/menuCSS.ts
packages/headless-styles/src/components/Menu/menuJS.ts

contributes to #500 
With feature disabled, menu API returns empty props.
With feature disabled, menu API returns `null`

feat(headless-styles): return null instead of props for disabled feature

---

packages/headless-styles/src/components/Select/generated/selectCSS.module.ts
packages/headless-styles/src/components/Select/selectCSS.module.css

Standard Select CSS includes style for multiple select
Multi-select style removed from the single-select CSS

fix(headless-styles): remove multiple select styles from standard select

---

website/docs/development/headless-styles/Select.mdx

contributes to #693 
Section about `optgroup` missing from Select docs
Adds section about using `optgroup` to organize Select options

docs(headless-styles): add optgroup example to Select docs

---

website/docs/development/react-utils/use-roving-tabindex.mdx

Contributes to #604
Adds documentation for `useRovingTabIndex` hook

docs(react-utils): add docs page for roving tab index hook

---

packages/headless-styles/src/utils/helpers.ts

In testing out headless styles, I found it difficult to know what styles were available to reference, because the `styles` entry on all of the `getJS*Props` functions is typed as `Record<string, unknown>`.
If these changes are accepted, it should improve type definitions on `getJS*Props` so that rather than just having all `styles` entries be `Record<string, unknown>`, it would use the actual values given and infer the types and show what selectors are actually used.

Narrow types for `createJSProps` and `createCSSObj` return values

---

packages/headless-styles/sandbox/src/components/Input.jsx
packages/headless-styles/src/components/Input/generated/InputCSS.module.ts
packages/headless-styles/src/components/Input/inputCSS.module.css
packages/headless-styles/src/components/Input/inputCSS.ts
packages/headless-styles/src/components/Input/inputJS.ts
packages/headless-styles/src/components/Input/shared.ts
packages/headless-styles/src/components/Select/chakraSelect.ts
packages/headless-styles/src/components/Select/generated/selectCSS.module.ts
packages/headless-styles/src/components/Select/selectCSS.module.css
packages/headless-styles/src/components/Select/selectCSS.ts
packages/headless-styles/src/components/Select/selectJS.ts
packages/headless-styles/src/components/Select/shared.ts
packages/headless-styles/tests/input/inputCSS.test.ts
packages/headless-styles/tests/select/selectCSS.test.ts

contributes to #869 
Moves `inputWrapper` to contain only the input and icons.  
This fits because the label and messages are technically separate, so containing them should be separate as well.
This also makes Input and Select more consistent
Removes the need for icon size classes.
Requires an update to documentation
Consider adding a field wrapper to the Form Control helper

fix: move input wrapper around just the input and icons

---

packages/headless-styles/npm/browser.js
packages/headless-styles/npm/index.js
packages/headless-styles/package.json
packages/headless-styles/rollup.config.mjs

All headless-styles components end up in one file (well, technically 4 - dev and prod builds for both ESM and CJS), which renders them un-tree-shakeable.
Generate separate files for each component, so that common tree-shaking algorithms can remove unused component CSS.
This also removes the 'development' build, as the only real difference between prod and dev is minification, which is more properly handled by the consuming application. It also means we no longer need bundler-specific tricks to make 'process.env' work properly.
Fixes #940 . See that issue for more details.

build(headless-styles): make headless-styles tree-shakeable

---

packages/headless-styles/npm/browser.js
packages/headless-styles/npm/index.js
packages/headless-styles/package.json
packages/headless-styles/rollup.config.mjs

Reverts pluralsight/tva#941
Builds are failing due to rollup creating a .yarn cache directory that isn't accessible to basic projects. See examples:
- Codesandbox: https://codesandbox.io/s/boring-leavitt-7zbdy4?file=/src/App.tsx
- https://stackblitz.com/edit/react-ts-nuqceg?file=App.tsx

Revert "build(headless-styles): make headless-styles tree-shakeable"

---

packages/headless-styles/src/components/Checkbox/checkboxCSS.module.css
packages/headless-styles/src/components/Checkbox/generated/checkboxCSS.module.ts
packages/headless-styles/src/components/Input/generated/InputCSS.module.ts
packages/headless-styles/src/components/Input/inputCSS.module.css
packages/headless-styles/src/components/Radio/generated/radioCSS.module.ts
packages/headless-styles/src/components/Radio/radioCSS.module.css
packages/headless-styles/src/components/Select/generated/selectCSS.module.ts
packages/headless-styles/src/components/Select/selectCSS.module.css
packages/headless-styles/src/components/Textarea/generated/textareaCSS.module.ts
packages/headless-styles/src/components/Textarea/textareaCSS.module.css

closes #866 
Updates border color of input elements

feat(headless-styles): update border color for inputs

---

packages/headless-styles/npm/browser.js
packages/headless-styles/npm/index.js
packages/headless-styles/package.json
packages/headless-styles/rollup.config.mjs

All headless-styles components end up in one file (well, technically 4 - dev and prod builds for both ESM and CJS), which renders them un-tree-shakeable.
Fixes #940 ; fixed version of #941
Generate separate files for each component, so that common tree-shaking algorithms can remove unused component CSS.
This also removes the 'development' build, as the only real difference between prod and dev is minification, which is more properly handled by the consuming application. It also means we no longer need bundler-specific tricks to make 'process.env' work properly.
In addition to the stuff in #941 , this PR uses `manualChunks` instead of `preserveModules` so that we have more control over …

Treeshake headless styles

---

.codesandbox/ci.json
packages/react-utils/src/hooks/menu/useMenuInteraction.ts
packages/react-utils/src/hooks/menu/useSubmenuInteraction.ts

closes #962 
Resolves error by moving focus after menu is rendered

fix(react-utils): don't move focus to first item until menu is rendered

---

packages/headless-styles/src/components/Checkbox/chakraCheckbox.ts
packages/headless-styles/src/components/Checkbox/checkboxCSS.module.css
packages/headless-styles/src/components/Checkbox/checkboxJS.ts
packages/headless-styles/src/components/Checkbox/generated/checkboxCSS.module.ts
packages/headless-styles/src/components/Checkbox/shared.ts
packages/headless-styles/src/components/Checkbox/types.ts
packages/headless-styles/src/components/Radio/chakraRadio.ts
packages/headless-styles/src/components/Radio/generated/radioCSS.module.ts
packages/headless-styles/src/components/Radio/radioCSS.module.css
packages/headless-styles/src/components/sharedDefaultOptions.ts
packages/headless-styles/tests/checkbox/checkboxCSS.test.ts
packages/headless-styles/tests/radio/radioCSS.test.ts

contributes #1001 
Updates Checkbox API to use `disabled` attribute
`:disabled` is only accepted with form elements. This is why we are using `[disabled]` here (it's applied to span and div).

refactor(hs): update Checkbox API to use disabled

---

packages/design-tokens/fonts.css
packages/design-tokens/styles/_core.scss
packages/design-tokens/styles/_typography.scss
website/docs/development/getting-started/installation.md
website/docusaurus.config.js
website/src/css/custom.css

closes #1068 
- updates DT typography to remove `font-variation-settings` from normalize setup
- updates PS font to use correct naming for both base and Italic fonts
- removes unused code fonts to help performance loading
- adds missing Display styles
Moz dev now recommends to only use `font-weight` and never use FVS property (it now says is too low level and may cause issues which is what we are seeing from Safari).
HS updates will come in next PR.
Sandbox: https://codesandbox.io/s/ps-react-typescript-forked-dke59m?file=/src/App.tsx

1068 bug preloading font script in safari

---

packages/headless-styles/src/components/Button/buttonCSS.ts
packages/headless-styles/src/components/Button/shared.ts
packages/headless-styles/src/components/Button/types.ts
packages/headless-styles/src/utils/helpers.ts
packages/headless-styles/src/utils/types.ts
packages/headless-styles/tests/button/buttonCSS.test.ts

contributes #1192 
- Adds new DefaultOptions interface
- Adds interface to ButtonOptions
- Updates ButtonCSS API to support custom classList
We will need to refactor some APIs to be composable like the new Alert/Toast APIs for this to be beneficial.
Sandbox: https://codesandbox.io/s/ps-react-typescript-forked-g54mt8?file=/src/App.tsx

feat(hs): add classNames option to Button

---

packages/headless-styles/src/components/Skeleton/skeletonCSS.module.css

contributes #1308 
Adds missing `:has` selector for the content Skeleton styles to hide non-text elements.
https://codesandbox.io/s/ps-react-typescript-forked-bxgruz?file=/src/App.tsx

fix(hs): add has selector to skeletonCSS.module.css

---

.github/workflows/contributing.yml

Main build failing on this action
Removes the `merge_group` trigger

ci: don't trigger doc comment on merge_group

---

packages/headless-styles/src/components/Badge/shared.ts
packages/headless-styles/src/components/Icon/iconCSS.ts
packages/headless-styles/src/components/Icon/shared.ts
packages/headless-styles/src/components/Icon/types.ts
packages/headless-styles/src/components/IconButton/shared.ts
packages/headless-styles/src/components/Input/shared.ts
packages/headless-styles/src/components/Select/shared.ts
packages/headless-styles/tests/badge/badgeCSS.test.ts
packages/headless-styles/tests/badge/badgeJS.test.ts
packages/headless-styles/tests/icon/iconCSS.test.ts
packages/headless-styles/tests/icon/iconJS.test.ts
packages/headless-styles/tests/iconButton/iconButtonCSS.test.ts

closes #1383 
Updates Icon types to conditionally use `ariaLabel` if `ariaHidden` is `false`.
TS made me do all that strict logic in order to be valid.
https://codesandbox.io/s/ps-react-typescript-forked-p8r8oj?file=/src/App.tsx

fix(hs): update Icon types to be conditional based on ariaHidden result

---

packages/react/src/components/Grid.tsx

forwards `area` and `areas` props to HS grid item and grid APIs, respectively
https://codesandbox.io/s/ps-react-typescript-forked-5o689z?file=/src/App.tsx

fix(react): forwards area and areas props for grid components

---

packages/react/src/components/tabs.tsx

When `disabled` is `undefined` in a Tab, the CircularProgress is still hidden because it is checking for `isPending` and `disabled`.
Updates the Tab to just use nativeProps.disabled and show CircularProgress when `isPending` only.

fix(react): update tabs to only use pending state

---

docs/src/content/docs/reference/colors/neutral-palette.mdx

Fixes #1939 
Modifies docs to reflect preset naming convention for neutral text colors
To test:
- run `bun run start:docs` to run docs on `localhost:4321`
- nav to http://localhost:4321/reference/colors/neutral-palette
Expected:
- see neutral text colors reflected

fix(docs): Update token naming in docs to match preset

---

docs/src/components/ColorSwatch.astro
docs/src/content/docs/reference/colors/neutral-palette.mdx

fixes #1926
Adds remaining neutral color palette colors to the neutral color reference page
reference [figma](https://www.figma.com/proto/uJtPfI38D9i8iQg0UGK2E0/Pando-Design-Guidelines?node-id=481-19600&starting-point-node-id=6%3A11626) to review current neutral color docs
https://github.com/pluralsight/pando/assets/146388897/2a58aa01-50c7-484e-b524-682df1f61a63

1926 (feat) fill out remaining neutral color tokens in docs

---

packages/react/src/index.ts
packages/react/tsup.config.ts

React lib still throwing errors for outdated types during refactor process
Fine tunes temp exports for .ts files

fix: only ship refactored .ts files in react

---

docs/package.json

#1990, #1987, #1984, #1993 all attempted to fix build errors for the new docs site. This is related to that effort - the build is [not passing yet](https://github.com/pluralsight/pando/actions/runs/7481397281/job/20362907566).
adds panda gen to build script to avoid missing styled-system dir

chore: add panda generate to build

---

docs/astro.config.mjs
docs/src/components/DocumentStatus.tsx
docs/src/components/TypographyHeader.astro
docs/src/content/docs/reference/typography.mdx

Closes #1965
Migrates essentially the first half of the [Typography Doc on the Figma Design Guidelines](https://www.figma.com/proto/uJtPfI38D9i8iQg0UGK2E0/Pando-Design-Guidelines?node-id=533-15987&starting-point-node-id=6%3A11626)
The doc felt like it was getting long and I know it is a lot of content so I decided to split this migration into 2 pr's -- the next PR will finish migrating the remaining typography content as well as make sure any typography content from beta docs is covered if necessary.
https://github.com/pluralsight/pando/assets/146388897/f57c2650-2fab-47ee-b165-b3267a1e1c94

1965 feat typography doc

---

docs/src/content/docs/index.mdx

closes #2000 
Adds front matter to populate a banner on the v1 docs landing page
This is the lowest weight option - it is possible to add banners to every markdown page's front matter, but it may be enough to indicate that the v1 docs are still wip on the landing page

feat(docs): content for banner on landing page

---

docs/astro.config.mjs
docs/src/components/DocumentStatus.tsx
docs/src/content/docs/explanation/color.mdx
docs/src/content/docs/reference/color/danger-palette.mdx
docs/src/content/docs/reference/color/warning-palette.mdx

closes #1964 
closes #2005 (bug)
* Adds danger palette ref page & navigation
* Updates color titles in to a font color of each color scheme
* This is the last color reference page - after this color will be complete, save for clarifying details for colors on specific sentiment reference pages
https://github.com/pluralsight/pando/assets/146388897/edc5f3d9-a32b-489f-a844-09c08cfdbb06

feat(docs): add danger palette & references

---

.github/workflows/docs_release.yml

#2035 made to update workflow deploy had made a change to the path which [broke the build in the deploy action](https://github.com/pluralsight/pando/actions/runs/7585993793) - this reverts that change as it had not been an issue before
reverts to previous path

chore: revert docs_release path change

---

.github/workflows/docs_release.yml

the docs deploy is still failing after https://github.com/pluralsight/pando/pull/2094 was merged with this error: `Failed to resolve entry for package "@pluralsight/icons". The package may have incorrect main/module/exports specified in its package.json.`
I resolved this locally and in the build check by running the icons build command. This includes that step in the deploy workflow.

ci(docs): add icon build to deploy workflow

---

.github/workflows/docs_release.yml

#2101 tried to run the icons build script to make fix deploy error `Failed to resolve entry for package "@pluralsight/icons". The package may have incorrect main/module/exports specified in its package.json.` but did not succeed. 
This puts the icons build step in another job and makes the build & upload step require icons build to complete before proceeding.

ci(docs): additional icon build job before build and upload step

---

.github/workflows/docs_release.yml

Deploying docs to gh-pages with `actions/deploy-pages@v4` is failing because it requires `actions/upload-pages-artifact@v4`. Astro's action `withastro/action@v1` uses `actions/upload-pages-artifact@v2`. This modifies the deploy-pages action to v3 to hopefully resolve the deploy issue - when `withastro/action@v2` is released we can revisit deploy-pages action version.
See https://github.com/withastro/action/pull/38 for additional details

chore(docs): update docs deploy-pages action

---

docs/src/components/ReactLib/ThemeSelect/ThemeSelectButton.tsx

the docs `ThemeSelectButton` uses a generic button to switch light/dark mode
swaps generic button for use Pando's `IconButton` 
* still observing color contrast issues with buttons, but that color work is still in progress and will be fixed when #2117 is resolved

feat(docs): swap generic button with pando iconbutton component

---

package.json

[docs deploy is failing](https://github.com/pluralsight/pando/actions/runs/8160995009/job/22308835501) because it is unable to find `@pluralsight/icons/icons.json` in the build. 
I think this issue may have popped up when I started using the workspace version of icons for icons.json for the categories for icon reference docs in PR #2220. This includes icons build in the docs build script to provide that dependency and hopefully fix docs deploy.

chore: build icons in docs build script

---

.github/workflows/docs_preview.yml

closes #2206 
Anyone who would like to clicktest a docs pr has to pull down the branch and run locally. Our team has worked with this, but it should not be required to view changes.
Adds gh action `rossjrw/pr-preview-action@v1` on pr's to deploy a preview on changes to the docs site
https://github.com/marketplace/actions/deploy-pr-preview

chore: add gh action to deploy preview

---

.github/workflows/docs_preview.yml

[docs preview failed](https://github.com/pluralsight/pando/actions/runs/8178941907/job/22363934182?pr=2230) because it could not find pnpm. It will also fail because it can not find bun
adds pnpm and bun to preview action

chore: add pnpm and bun to preview action

---

docs/src/content/docs/reference/available-in-v1.mdx

The [Available in v1](https://pando.pluralsight.com/reference/available-in-v1/) doc reflected the components commented & uncommented in `/packages/react/src/index.ts`. That file does not fully reflect all components meant to be made available in v1.
Updates available in v1 doc to match remaining components coming soon

docs: update coming soon components to match beta
