pluralsight/pando

- CONTRIBUTING.md
- README.md
Update to docs
- Adds README.md
- Adds CONTRIBUTING.md
contributes to #1
> [docs]: add initial md files

- .github/workflows/issues.yml
contributes #1
There is no cleanup for Question issues created by human error.
Updates the GH workflows to automate closing incorrectly placed Question issues.
> [Feature]: add GH issues workflow

- README.md
contributes #1 
Updates contributing section of README
> [Docs]: update README.md

- .github/workflows/tests.yml
- dangerfile.js
contributes to #1 
Danger exists but not being used in PR process.
Updates Actions to run a danger job for PR's.
> ci: add dangerjs action to tests.yml

- .github/workflows/documentation.yml
- CONTRIBUTING.md
- README.md
- package.json
- website/README.md
- website/docusaurus.config.js
contributes to #14 
No CI setup to manage doc releases.
Adds documentation.yml to GH actions workflows.
> [docs]: add ci deployment

- .github/workflows/documentation.yml
- CONTRIBUTING.md
- website/README.md
- website/docs/intro.md
- website/docusaurus.config.js
contributes to #14 
Deploy step just added.
n/a
Testing to see if it works.
> docs: deploy test 1

- .github/workflows/contributing.yml
contributes to #44 
DangerJS works for repo but not forks.
Moves Danger checks to GH action.
> [ci]: add contributing.yml

- .github/workflows/contributing.yml
- website/README.md
contributes to #44 
PR commenter works, but fails on forked PR's
> ci: add pr_target to contributing.yml for forks

- scripts/release/publish-commands/print-follow-up-instructions.mjs
- scripts/release/publish.js
- scripts/theme.mjs
closes #67 
Adds follow up instructions for non-ci post-publish commands
> ci: add follow up instructions for manual publish

- website/docs/development/getting-started/support.md
Change it's (it is) to its (possessive)
> tiny grammar change

- packages/tokens/package.json
closes #77 
Updates `tokens` package.json `files` setting to only include web-related files.
> feat(tokens): update files field in package.json

- .codesandbox/ci.json
closes #78 
Updates PR's to use code sandbox for API testing
This configuration allows codesandbox to run the `build` command on each package listed so we can test any updates in a 3rd party environment to ensure we are not pushing breaking changes to npm.
> ci: add codesandbox pr setup

- normalize.css
closes #85 
Adds normalize.css to repo as config file since it will be hosted on our CDN and rarely if ever changed.
> feat: add normalize.css

- website/docs/development/getting-started/installation.md
- website/docs/development/packages/tokens/colors.mdx
contributes to #100 
All the errors that were never pushed up due to accidental approval/merge.
> chore: fix grammar errors

- packages/design-tokens/config.js
- packages/design-tokens/package.json
closes #114 
Updates config to export `index.d.ts` for TS users.
> build(tokens): add TS config for type definitions

- packages/design-tokens/package.json
design-tokens not shipping all files due to change in `files` value.
Reverts property to use original value.
> revert(tokens): change files back to original value

- website/docusaurus.config.js
- website/static/CNAME
Site broken since now using design.pluralsight.com
Updates config to use new url
> fix: update website config to use design.pluralsight.com

- website/docs/development/getting-started/installation.md
- website/docs/development/getting-started/usage.md
- website/docs/development/packages/icons/_category_.yml
- website/docs/development/packages/icons/intro.md
No icons info present.
Adds icons section to packages.
> docs: add initial icons to packages section

- .github/workflows/publish_prereleases.yml
- packages/icons/README.md
Icons package is throwing CI error (wrong), but still successfully publishing new packages (right).
Confirmation PR to ensure CI is working properly now that package and all tags exist.
> test: confirm icons publish in CI

- jest.config.js
- packages/headless-styles/src/components/Button/buttonCSS.module.css
- packages/headless-styles/src/components/Button/buttonJS.ts
- packages/headless-styles/tests/button/buttonJS.test.ts
- packages/headless-styles/tests/button/fixtures/getButtonPropsCSS.ts
- packages/headless-styles/tests/button/fixtures/getButtonPropsJS.ts
- website/docs/development/packages/headless-styles/Button.mdx
contributes to #108 
Adds styles the work within the MUI world for the `getButtonProps` helpers
JS testing got weird, so I had to update them.
> feat: add MUI styles to `getButtonProps` helpers

- .eslintrc.js
- packages/headless-styles/src/components/Button/buttonCSS.module.css
- packages/headless-styles/src/components/Button/buttonJS.ts
contributes to #108 
Adds chakra styles to `getButtonProps` helpers
If people eventually don't like the !important everywhere (i.e. it makes it too strict), I have a future solution to add to the API. So as of now, I'm not worried about it.
> feat(hs): add chakra styles to getButtonProps

- .pnp.cjs
- website/docusaurus.config.js
- website/package.json
- website/src/css/custom.css
- yarn.lock
closes #127 
Adds official search configuration settings & updates styles
> docs: add algolia search & update styles

- packages/design-tokens/fonts.css
- packages/design-tokens/normalize.css
closes #135 
* New Web UI kit changes how font & spacing is used to be more a11y focused
* Updates other settings to use correct formats
> refactor(tokens): update fonts & normalize to use new font settings

- website/docs/development/getting-started/migration.md
I'm pretty sure that's right, I also just wanted to see if I could figure out a pull request
> fixed typo

- website/docs/development/packages/tokens/colors.mdx
Custom theming info was missing in docs.
Adds info in the colors.mdx file for tokens
> docs: add custom theming section to colors.mdx

- website/docs/development/packages/icons/intro.md
- website/docs/development/packages/icons/usage.mdx
- website/src/components/Icons/BasicIcon.preview.js
- website/src/components/Icons/IconColor.preview.js
- website/src/components/Icons/IconSizes.preview.js
Categorization noted as matching MUI icon categories
Categorization references updated to match our current design files
> docs(icons): update icon categorization details to align with design

- .vscode/extensions.json
- packages/headless-styles/src/components/Button/buttonCSS.ts
- packages/headless-styles/src/components/Button/types.ts
- packages/headless-styles/tests/button/buttonCSS.test.ts
- website/docs/development/packages/headless-styles/Button.mdx
closes #173 
Updates `getButtonProps` to return a `rawClass` prop for Svelte components to use.
> feat(hs): update getButtonProps to use rawClass for Svelte apps

- website/src/components/LiveExampleTabs/LiveExampleTabs.js
- website/src/components/LiveExampleTabs/LiveExampleTabs.module.css
Svelte example icon was using codesandbox fallback
Adds Svelte logo.
> docs: update LiveExamplesTabs to use Svelte icon

- packages/headless-styles/sandbox/src/App.jsx
- packages/headless-styles/sandbox/src/components/Badge.jsx
- packages/headless-styles/sandbox/src/components/Button.jsx
- packages/headless-styles/src/components/Badge/badgeJS.ts
- packages/headless-styles/src/components/Badge/generated/badgeCSS.module.ts
- packages/headless-styles/src/index.ts
- packages/headless-styles/src/utils/helpers.ts
- packages/headless-styles/tests/badge/badgeJS.test.ts
- packages/headless-styles/tests/utils/helpers.test.ts
closes #180 
Adds JS API for the Badge component
> feat(hs): add badgeJS and helpers

- packages/headless-styles/src/components/Badge/badgeJS.ts
- packages/headless-styles/src/components/Badge/shared.ts
- packages/headless-styles/src/components/Badge/types.ts
contributes to #184 
Adds additional export for MUI to prevent adding unnecessary logic to the default fuction since it's MUI specific.
> feat(hs): add MUI label override export

- packages/headless-styles/src/index.ts
closes #184 
Adds public export for `muiLabelOverride`
> feat(hs): add muiLabelOverride to main exports

- website/docs/development/getting-started/installation.md
- website/docs/development/packages/headless-styles/Button.mdx
- website/docs/development/packages/headless-styles/intro.md
closes #179 
Adds intro page to headless-styles
> docs: add headless-styles intro page

- packages/headless-styles/sandbox/src/components/Button.jsx
- packages/headless-styles/src/chakra.ts
- packages/headless-styles/src/components/Button/buttonCSS.module.css
- packages/headless-styles/src/components/Button/buttonCSS.ts
- packages/headless-styles/src/components/Button/buttonJS.ts
- packages/headless-styles/src/components/Button/generated/buttonCSS.module.ts
- packages/headless-styles/src/components/Button/shared.ts
- packages/headless-styles/src/components/Button/types.ts
- packages/headless-styles/src/index.ts
- packages/headless-styles/tests/button/buttonCSS.test.ts
- packages/headless-styles/tests/button/buttonJS.test.ts
contributes to #212 
* Updates both CSS & JS Button API to use latest standards for HS components
* Adds ChakraButton config
> refactor: update Button API to use latest standards

- .markdownlint.json
- .vscode/extensions.json
- website/docs/development/getting-started/faq.md
- website/docs/development/getting-started/installation.md
- website/docs/development/getting-started/migration.md
- website/docs/development/getting-started/support.md
- website/docs/development/getting-started/usage.md
- website/docs/development/getting-started/usage_mobile.md
- website/docs/development/packages/headless-styles/Button.mdx
- website/docs/team.md
NO ISSUE
* General cleanup to remove TVA instances and make the Button API more accessible. 
* Adds Markdownlint extension and config
Will update other HS APIs to match in future.
> docs: cleanup TVA & Button API

- packages/headless-styles/sandbox/src/App.jsx
- packages/headless-styles/sandbox/src/components/Progress.jsx
- packages/headless-styles/src/chakra.ts
- packages/headless-styles/src/components/Progress/progressCSS.ts
- packages/headless-styles/src/components/Progress/progressJS.ts
- packages/headless-styles/src/components/Progress/shared.ts
- packages/headless-styles/src/components/Progress/types.ts
- packages/headless-styles/src/index.ts
contributes to #219 
* Adds progressJS API
* Adds ChakraProgress styles
> feat: add progressJS api

- packages/icons/package.json
- packages/icons/svgo.config.cjs
- packages/icons/tests/utils/squareViewBox.test.js
- packages/icons/utils/squareViewBox.cjs
closes #223 
Some icons have rectangular viewBoxes, which may cause alignment issues.  
Rectangular viewBoxes will be expanded to be square such that the image itself is not changed - the aspect ratio and original offsets are preserved.
> feat(icons): add svgo plugin to square viewBox attribute

- packages/headless-styles/sandbox/src/App.jsx
- packages/headless-styles/sandbox/src/components/CircularProgress.jsx
- packages/headless-styles/src/components/CircularProgress/circularProgressCSS.ts
- packages/headless-styles/src/components/CircularProgress/circularProgressJS.ts
- packages/headless-styles/src/components/CircularProgress/shared.ts
- packages/headless-styles/src/index.ts
- packages/headless-styles/tests/circular-progress/circularProgressJS.test.ts
contributes #220 
* Refactors some shared code
* Adds "xs" styles
* Adds JS API
> feat: add getJSCircularProgressProps API

- packages/headless-styles/sandbox/src/components/CircularProgress.jsx
- packages/headless-styles/src/chakra.ts
- packages/headless-styles/src/components/CircularProgress/circularProgressCSS.module.css
- packages/headless-styles/src/components/CircularProgress/circularProgressCSS.ts
- packages/headless-styles/src/components/CircularProgress/circularProgressJS.ts
- packages/headless-styles/src/components/CircularProgress/generated/circularProgressCSS.module.ts
- packages/headless-styles/tests/circular-progress/circularProgressCSS.test.ts
- packages/headless-styles/tests/circular-progress/circularProgressJS.test.ts
contributes #220 
Adds `ChakraCircularProgress`
> feat(hs): add ChakraCircularProgress

- website/docs/development/packages/icons/usage.mdx
closes #249 
Examples did not link to code sandboxes
Codesandbox contents updated to reference the package and links added to documentation.
> docs(icons): add links to codesandbox examples

- website/docs/development/packages/headless-styles/Icon.mdx
- website/docs/development/packages/icons/usage.mdx
- website/src/components/Icons/BasicIcon.js
- website/src/components/Icons/IconSizes.js
- website/src/components/Icons/IconSizes.preview.js
contributes to #270 
Documentation to reflect changes in available icon size settings
> docs(headless-styles): update available sizes

- packages/headless-styles/sandbox/src/components/FormLabel.jsx
- packages/headless-styles/src/components/FormLabel/formLabelCSS.ts
- packages/headless-styles/src/components/FormLabel/formLabelJS.ts
- packages/headless-styles/src/components/FormLabel/shared.ts
- packages/headless-styles/src/components/FormLabel/types.ts
- packages/headless-styles/tests/formLabel/formLabelCSS.test.ts
- packages/headless-styles/tests/formLabel/formLabelJS.test.ts
contributes #287 
Updates FormLabel API to include `required` option and return `value`
> feat: add label required option

- packages/headless-styles/sandbox/src/components/Radio.jsx
- packages/headless-styles/src/chakra.ts
- packages/headless-styles/src/components/Radio/generated/radioCSS.module.ts
- packages/headless-styles/src/components/Radio/radioCSS.module.css
- packages/headless-styles/src/components/Radio/radioJS.ts
- packages/headless-styles/src/components/Switch/generated/switchCSS.module.ts
- packages/headless-styles/src/components/Switch/switchCSS.module.css
- packages/headless-styles/src/index.ts
- packages/headless-styles/tests/radio/radioJS.test.ts
- packages/headless-styles/tests/switch/switchJS.test.ts
contributes #285 
* Adds Radio JS API
* Adds Radio chakra API
Will make a hotfix Switch PR to add all the new styles into the JS API after this one.
> feat(hs): add radioJS API

- packages/headless-styles/sandbox/src/App.jsx
- packages/headless-styles/src/components/Switch/switchJS.ts
closes #298 
Adds missing Switch styles to JS & Chakra API
> fix(hs): add missing Switch styles to JS API

- website/docs/development/packages/headless-styles/Radio.mdx
Radio page was missing sandbox links
Adds radio sandbox links
> docs(dev): add missing sandbox links to Radio.mdx

- packages/headless-styles/sandbox/src/App.jsx
- packages/headless-styles/sandbox/src/components/ErrorMessage.jsx
- packages/headless-styles/src/chakra.ts
- packages/headless-styles/src/components/Button/generated/buttonCSS.module.ts
- packages/headless-styles/src/components/ErrorMessage/errorMessageCSS.ts
- packages/headless-styles/src/components/ErrorMessage/errorMessageJS.ts
- packages/headless-styles/src/components/ErrorMessage/shared.ts
- packages/headless-styles/src/components/ErrorMessage/types.ts
- packages/headless-styles/src/index.ts
- packages/headless-styles/src/utils/helpers.ts
- packages/headless-styles/tests/errorMessage/errorMessageCSS.test.ts
- packages/headless-styles/tests/errorMessage/errorMessageJS.test.ts
contributes #305 
* Adds JS & Chakra API
> feat(hs): add ErrorMessage JS API

- packages/icons/package.json
- yarn.lock
closes #313 
Adds react as an optional peer dependency
> fix(icons): mark React as peer dependency

- packages/headless-styles/sandbox/src/App.jsx
- packages/headless-styles/sandbox/src/components/Input.jsx
- packages/headless-styles/src/components/Input/inputJS.ts
- packages/headless-styles/src/index.ts
- packages/headless-styles/tests/input/inputJS.test.ts
contributes to #308 
Adds JS Input API
> feat(hs): add JS input API

- packages/headless-styles/src/components/Badge/badgeCSS.ts
- packages/headless-styles/src/components/Badge/shared.ts
- packages/headless-styles/src/components/Badge/types.ts
Contributes to #312 
Replace separate class prop helpers with the singular helper `createClassProp`
> refactor(headless-styles): use createClassProp for Badge API

- packages/headless-styles/src/components/FormControl/formControlCSS.ts
- packages/headless-styles/src/components/FormControl/shared.ts
- packages/headless-styles/src/components/FormControl/types.ts
Contributes to #312 
Uses class helper in FormControl
> refactor(headless-styles): use class prop helper for formControl

- packages/headless-styles/src/components/Icon/iconCSS.ts
- packages/headless-styles/src/components/Icon/shared.ts
- packages/headless-styles/src/components/Icon/types.ts
contributes to #312 
use class helper in icon api
> refactor(headless-styles): use class helper for icon api

- packages/headless-styles/src/components/Skeleton/shared.ts
- packages/headless-styles/src/components/Skeleton/skeletonCSS.ts
- packages/headless-styles/src/components/Skeleton/types.ts
Contributes to #312 
Uses class helper in skeleton API
> refactor(headless-styles): use class helper for skeleton api

- packages/headless-styles/src/components/Progress/progressCSS.ts
- packages/headless-styles/src/components/Progress/shared.ts
- packages/headless-styles/src/components/Progress/types.ts
contributes to #312 
Uses class helper in progress api
> refactor(headless-styles): use class helper for progress api

- packages/headless-styles/sandbox/src/App.jsx
- packages/headless-styles/sandbox/src/components/Checkbox.jsx
- packages/headless-styles/src/chakra.ts
- packages/headless-styles/src/components/Checkbox/chakraCheckbox.ts
- packages/headless-styles/src/components/Checkbox/checkboxCSS.ts
- packages/headless-styles/src/components/Checkbox/checkboxJS.ts
- packages/headless-styles/src/components/Checkbox/shared.ts
- packages/headless-styles/src/components/Radio/chakraRadio.ts
- packages/headless-styles/src/index.ts
- packages/headless-styles/tests/checkbox/checkboxJS.test.ts
contributes #349 
* Adds Checkbox JS API
* Adds Checkbox Chakra API
Refactors chakraRadio into it's own file to match new pattern.
> feat(hs): add checkboxJS & chakraCheckbox

- packages/icons/svgo.config.cjs
fixes #359 
xmlns attribute was removed from SVGs 
xmlns attribute no longer removed
> fix(icons): do not remove xmlns from exported svgs

- website/docs/development/headless-styles/Badge.mdx
- website/docs/development/headless-styles/Button.mdx
- website/docs/development/headless-styles/Checkbox.mdx
- website/docs/development/headless-styles/CircularProgress.mdx
- website/docs/development/headless-styles/FormControl.mdx
- website/docs/development/headless-styles/Icon.mdx
- website/docs/development/headless-styles/Input.mdx
- website/docs/development/headless-styles/Progress.mdx
- website/docs/development/headless-styles/Radio.mdx
- website/docs/development/headless-styles/Skeleton.mdx
- website/docs/development/headless-styles/Switch.mdx
contributes #366 
closes #300 
closes #291 
* Updates all HS API pages to use the same structure
* Adds all missing type information for options
> docs(dev): make all API pages consistent

- packages/headless-styles/src/chakra.ts
- packages/headless-styles/src/components/Textarea/chakraTextarea.ts
closes #379 
Adds ChakraTextarea
> feat(hs): add chakraTextarea.ts

- packages/headless-styles/src/chakra.ts
- packages/headless-styles/src/components/Button/buttonJS.ts
- packages/headless-styles/src/components/Button/chakraButton.ts
closes #172 
Adds icon button variations to chakra button.
> feat(headless-styles): move chakra button and add icon button styles

- packages/headless-styles/sandbox/src/components/ButtonWithIcon.jsx
- packages/headless-styles/src/index.ts
- packages/headless-styles/tests/button/buttonWithIconCSS.test.ts
contributes to #339 
adds getDangerButtonWithIconProps API
> feat(headless-styles): add getDangerButtonWithIcon CSS API

- website/docs/development/headless-styles/Icon.mdx
Spelling error on the Icon page code example.
Correct spelling error.
> chore: fix spelling error in Icon.mdx code example

- packages/headless-styles/src/chakra.ts
- packages/headless-styles/src/components/Alert/chakraAlert.ts
closes #406 
Adds Chakra & MUI styles
> feat(hs): add Chakra Alert styles

- website/docs/development/headless-styles/intro.mdx
closes #413 
Adds z-index map to headless-styles/intro page
> docs(hs): add z-index values to intro.mdx

- packages/headless-styles/sandbox/src/components/AlertDialog.jsx
contributes #414 
Updates sandbox example to use all closing feature requirements for a11y.
> feat(hs): add all closing options to AlertDialog.jsx example

- packages/headless-styles/src/chakra.ts
- packages/headless-styles/src/components/AlertDialog/chakraAlertDialog.ts
closes #414 
* Adds chakraAlertDialog
> feat(hs): create chakraAlertDialog.ts

- packages/headless-styles/src/chakra.ts
- packages/headless-styles/src/components/Avatar/chakraAvatar.ts
closes #446 
Adds Chakra theme for Avatar
> feat(headless-styles): add Chakra theme for Avatar

- website/blog/authors.yml
- website/docs/development/discover-more/_category_.yml
- website/docs/development/react-utils/_category_.yml
- website/docs/development/react-utils/intro.mdx
- website/docs/development/react-utils/use-focus-trap.mdx
closes #458 
Adds react-utils section and useFocusTrap API page.
> docs(development): add useFocusTrap API

- packages/react-utils/src/hooks/useEscToClose.ts
- packages/react-utils/src/index.ts
- packages/react-utils/tests/hooks/useEscToClose.test.tsx
closes #472 
Adds useEscToClose custom hook
> feat(react-utils): add useEscToClose API

- packages/headless-styles/src/chakra.ts
- packages/headless-styles/src/components/TextLink/chakraTextLink.ts
- packages/headless-styles/src/components/TextLink/shared.ts
closes #418 
Adds Chakra theme for Link
> feat(headless-styles): add Chakra theme for Link

- packages/design-tokens/data.config.cjs
- packages/design-tokens/package.json
- packages/design-tokens/utils/formats/dataSources.cjs
- packages/design-tokens/utils/vars.cjs
Website failing to import json file due to missing subpath definition in the "exports" field of package.json.
Adds it and support for commonJS for cssProps file.
> feat(tokens): add subpath exports & commonJS support

- packages/design-tokens/tokens/public/light.yaml
closes #493 
Updates light tokens to match dark
> fix(tokens): make light theme match dark

- packages/headless-styles/sandbox/src/App.jsx
- packages/headless-styles/sandbox/src/components/Button.jsx
- packages/headless-styles/src/components/Button/buttonJS.ts
- packages/headless-styles/src/components/Button/types.ts
- packages/headless-styles/src/index.ts
- packages/headless-styles/tests/button/buttonCSS.test.ts
- packages/headless-styles/tests/button/buttonJS.test.ts
contributes #495
Adds buttonJS API & tests
> refactor(headless): add ButtonJS API & tests

- packages/headless-styles/src/components/Checkbox/checkboxCSS.module.css
- packages/headless-styles/src/components/Checkbox/generated/checkboxCSS.module.ts
contributes to #486 
In light theme, (old) checkbox font color blends with background.
updates font color of checked checkbox to use active font color, matching the background.
> feat(headless-styles): update checked font color to new token value

- packages/design-tokens/data.config.cjs
- packages/design-tokens/package.json
- packages/design-tokens/utils/vars.cjs
closes #507 
Adds type decl. file for meta tokens to data config.
> feat(tokens): add type def file for cssProperties

- packages/design-tokens/styles/base.css
closes #530 
Updates base list styles to match Figma designs
Lists using icons would be a new HS API, which may be added later.
> feat(design-tokens): update base list typography styles

- packages/design-tokens/styles/base.css
This reverts commit ebdadf4566dc5e0604f6aab8925ffbdbae4bd046.
closes #545 
Reverts list typography base styles
> Revert "feat(design-tokens): update base list typography styles"

- .pnp.cjs
- packages/headless-styles/package.json
- packages/headless-styles/src/components/Menu/menuCSS.ts
- packages/headless-styles/src/globalJS.d.ts
- packages/shared/package.json
- versions.mjs
- yarn.lock
contributes #538 
HS was breaking due to expecting shared to be a public package - converts shared into a public package
> build: convert shared to public package

- .github/workflows/publish_experimental_release.yml
- .github/workflows/publish_next_release.yml
contributes #538 
Adds dynamic CI install of shared package into HS per environment
> ci: add dynamic hs package update

- versions.mjs
remove shared package from versions.mjs
> build: remove shared package from version file

- .codesandbox/ci.json
- package.json
- packages/headless-styles/src/components/Menu/menuJS.ts
menuJS.ts references `process.env.MENU_API` directly, causing errors when using.
Uses the shared package for feature flags
> fix(headless-styles): update menuJS feature flag to latest pattern

- .github/workflows/publish_stable_releases.yml
contributes #538 
Adds missing version and perpare:flags to stable workflow
> ci: add version and env.release_channel to stable script

- packages/shared/src/featureFlags.js
feature flags only contained EXPERIMENTAL logic.
Adds all channels for future use.
> feat(shared): add all flag options in featureFlags

- website/docs/development/getting-started/installation.md
- website/docs/development/getting-started/migration.md
- website/docs/development/getting-started/platforms.md
- website/docs/development/getting-started/support.md
- website/docs/development/getting-started/usage.md
contributes #576 
Updates dev/getting started pages
> docs: update getting started section

- website/blog/2022-09-14-dev-alpha/index.md
closes #573 
Adds release blog for alpha
> docs: alpha release notes

- website/docs/development/headless-styles/Menu.mdx
closes #587 
Adds content detailing the parameters for getMenuProps
> docs(headless-styles): add descriptions of getMenuProps arguments

- packages/shared/src/featureFlags.js
- [] Tests for the changes have been added (for bug fixes / features)
contributes #505 
Adds feature flag for preload Hook
> feat(shared): add preloadImgHook to flags

- website/src/css/custom.css
Fixes some list override selectors in docs site
> fix(website): update selectors to account for production class names

- packages/shared/src/index.ts
Some environments are not building correctly when exporting via wildcard (`export * from ...`)
Explicitly export feature flags in the index
> fix(shared): use explicit exports instead of wildcard

- .codesandbox/ci.json
- .vscode/settings.json
- netlify.toml
- package.json
> ci: update script to use release channel and shared

- .eslintrc.js
- eslint.config.js
- packages/shared/scripts/processFlags.mjs
- packages/shared/src/utils/helpers.ts
contributes #505 
Updates shared script to remove Netflify vars if building packages for NPM
> ci(shared): update processFlags to remove netlify if in GH CI

- packages/shared/src/index.ts
tabs feature flag missing from export list
Adds tabs flag to export
> fix(shared): add tabs flag to export list

- packages/shared/src/featureFlags.ts
- packages/shared/src/index.ts
- packages/shared/tests/flags/experimental.test.ts
- packages/shared/tests/flags/next.test.ts
contributes #618 
Adds tabsHook flag
> feat(react-utils): add useHook flag

- packages/headless-styles/sandbox/src/components/ConfirmDialog.jsx
- packages/react-utils/src/hooks/useFocusTrap.ts
- packages/react-utils/tests/hooks/useFocusTrap.test.tsx
closes #625 
Updates return value to use same syntax as React lib for consistency.
> fix(react-utils): correct spelling error in return props of useFocusTrap

- website/docs/development/react-utils/use-tabs.mdx
Typos for `TabsProvider` import
Corrects the spelling
> docs(dev): fix type in useTabs.mdx

- website/docs/development/getting-started/installation.md
- website/docs/development/getting-started/migration.md
- website/src/css/custom.css
> docs: update normalize links for new build path

- website/docs/development/getting-started/installation.md
- website/versioned_docs/version-0.1.0-alpha/development/getting-started/installation.md
Normalize links showing old versions
Make links use specific versions while in pre-release
> docs: update design-tokens to use specific versions

- packages/headless-styles/src/components/Input/inputJS.ts
> fix(headless-styles): add missing bracket to inputJS iconWrapper output

- packages/headless-styles/rollup.config.mjs
contributes #672 
Updates rollup output path to match what's in npm entry.
> fix(hs): update rollup to use entry paths used in npm

- packages/design-tokens/normalize.scss
- packages/design-tokens/styles/base.css
- versions.mjs
closes #687 
Adds `background-color` and `color` props to `html` selector for quicker startup in v2
> feat(tokens): update base to set bgc and color properties

- packages/headless-styles/src/components/Table/chakraTable.ts
contributes #669 
Updates ChakraTable styles
> feat(hs): update ChakraTable styles

- packages/headless-styles/src/chakra.ts
- packages/headless-styles/src/components/Select/chakraSelect.ts
closes #692 
Adds Chakra theme for `Select`
> feat(headless-styles): add Chakra theme for Select

- packages/headless-styles/index.stable.js
- packages/shared/src/featureFlags.ts
- packages/shared/tests/flags/experimental.test.ts
- packages/shared/tests/flags/stable.test.ts
Promotes Select APIs to 'next'
> feat(headless-styles): promote Select to stable

- packages/headless-styles/index.experimental.js
- packages/headless-styles/index.stable.js
- packages/shared/src/featureFlags.ts
- packages/shared/tests/flags/experimental.test.ts
- packages/shared/tests/flags/stable.test.ts
contributes #703 
Moves pagination flag to next
> feat(shared): promote pagination flag to next

- website/src/components/Select/Select.preview.js
"Select" documentation showing `unstable_` prefix in code samples.
Prefix removed
> docs: remove prefix from Select code examples

- website/docs/design/avatar.md
Closes #721 
No current Avatar design page.
Adds Avatar design page.
> docs: added avatar page

- website/docs/design/confirm-dialog.md
Closes #731 
No Confirm Dialog design page present
Adds Confirm Dialog design page.
> docs: added confirm dialog page

- packages/design-tokens/tokens/base/action.yaml
- packages/design-tokens/tokens/base/default.yaml
closes #735 
Updates default-text and navigation-visited colors
> feat(tokens): update default-text & navigation-visited values

- packages/design-tokens/tokens/base/action.yaml
closes #742 
Adds new `action-border-focus` token to theme
> feat(tokens): add action-border-focus token

- packages/design-tokens/tokens/public/color.yaml
- packages/design-tokens/tokens/public/light.yaml
- packages/design-tokens/tokens/public/lightJS.yaml
contributes #744
Adds `action-border-focus` to public tokens
> feat(tokens): add border-focus to public tokens

- packages/shared/src/featureFlags.ts
- packages/shared/src/index.ts
- packages/shared/tests/flags/experimental.test.ts
contributes to #603 
Adds experimental feature flags for menu-related hooks
> feat(shared): add menu hook experimental feature flags

- packages/react-utils/index.experimental.js
- packages/react-utils/src/hooks/useRovingTabIndex.ts
- packages/react-utils/src/index.ts
- packages/react-utils/tests/hooks/useRovingTabIndex.test.tsx
Contributes to #603 
Adds a hook for handling tabindex attribute when using a roving tabindex pattern
> feat(react-utils): add hook for roving tabindex

- website/docs/development/getting-started/migration.md
Migration page had outdated information.
Updates the page with the latest examples and recommendations via the Beta API.
Click the Netlify preview link to see a PR build of the docs.
> docs: update migration.md to match latest standards

- website/docs/design/modal.md
Closes #771 
No Modal design page present.
Adds a Modal design page.
> docs: added modal page

- packages/headless-styles/sandbox/src/components/Grid.jsx
- packages/headless-styles/src/components/Grid/gridJS.ts
- packages/headless-styles/src/index.ts
- packages/headless-styles/tests/grid/gridJS.test.ts
> feat(hs): add GridJS API and tests

- website/docs/design/radio.md
Closes #759 
No Radio design page present.
Adds a Radio design page.
> docs: added radio page

- website/docs/design/admonition.md
> docs: add admonition page

- website/docs/design/grammar.md
> docs: add grammar page

- website/docs/design/checkbox.md
Closes #729 
No current Checkbox design guidelines page.
Adds Checkbox design guidelines page.
> docs: added checkbox page

- website/docs/design/switch.md
Closes #763 
No Switch design guidelines page present.
Adds a Switch design guidelines page.
> docs: added switch page

- website/docs/design/lists.md
Closes #766 
No current Lists design page
Adds Lists design page
> docs: added lists page

- website/docs/design/menu.md
Closes #768 
No current Menu design page.
Adds Menu design page.
> docs: added menu page

- packages/headless-styles/index.experimental.js
- packages/headless-styles/index.stable.js
- packages/shared/src/featureFlags.ts
- packages/shared/tests/flags/experimental.test.ts
- packages/shared/tests/flags/stable.test.ts
contributes #781 
Promotes the grid flag to stable
> feat(shared): promote grid flag to stable

- website/docs/design/components/table.md
Closes #795 
No Table design guidelines page.
Adds Table design guidelines page.
> docs: added table page

- packages/headless-styles/package.json
- packages/headless-styles/rollup.config.mjs
- packages/headless-styles/tsconfig.json
contributes #740 
Adds types field to new "/styles" sub-path
> feat(hs): add TS types to exports declaration

- website/docs/development/headless-styles/FormControl.mdx
- website/docs/development/headless-styles/customization/components.mdx
closes #813 
Adds disclaimer section to customize docs to ensure users understand the consequences if doing so.
> docs(dev): add disclaimers section to components.mdx

- website/docs/design/components/tabs.md
Closes #803 
No Tabs design page.
Adds Tabs design page.
> docs: added tabs page

- website/docs/design/components/tooltip.md
Closes #826 
No current Tooltip design guidelines page.
Adds Tooltip design guidelines page.
> docs: add tooltip page

- packages/headless-styles/index.stable.js
- packages/headless-styles/rollup.config.mjs
- packages/headless-styles/src/components/Popover/popoverCSS.ts
- packages/headless-styles/src/components/Popover/popoverJS.ts
contributes to #801 
Removes popover feature flag logic in preparation for release
> feat(headless-styles): remove feature flag logic for popover

- .github/workflows/linting.yml
- .github/workflows/publish_stable_releases.yml
- .github/workflows/tests.yml
- scripts/release/prepare-npm-release-commands/check-out-packages.mjs
- scripts/release/prepare-release-from-npm.js
contributes #801 
- Validating stable release scripts work as planned
- Add naming meta to files for better CI experience
> ci: test naming props

- packages/headless-styles/sandbox/src/components/Input.jsx
- packages/headless-styles/sandbox/src/components/Select.jsx
- packages/headless-styles/src/components/ErrorMessage/errorMessageCSS.module.css
- packages/headless-styles/src/components/ErrorMessage/errorMessageJS.ts
- packages/headless-styles/src/components/ErrorMessage/generated/errorMessageCSS.module.ts
- packages/headless-styles/src/components/FieldMessage/fieldMessageCSS.module.css
- packages/headless-styles/src/components/FieldMessage/fieldMessageJS.ts
- packages/headless-styles/src/components/FieldMessage/generated/fieldMessageCSS.module.ts
contributes #801 
Last minute fine tuning for beta release
> fix(hs): fine tune styling for Beta

- packages/shared/src/featureFlags.ts
- packages/shared/src/index.ts
- packages/shared/tests/flags/experimental.test.ts
contributres to #801 
Removes popover feature flag
> feat: remove popover feature flag

- versions.mjs
closes #801 
Updates versions to support beta
> build: update versions for beta release

- versions.mjs
Versions outdated at 0.2.0
Updates to next Beta release 0.3.1
> build: update versions to 0.3.1

- website/docs/design/components/progress.md
Closes #853 
No Progress design components page
Adds Progress design guidelines page.
> docs: added progress page

- website/blog/2022-011-30-dev-beta/index.md
Blog missing Beta release notes
Adds them
> docs(blog): add beta release notes

- website/blog/2022-011-30-dev-beta/index.md
Casey can't grammar well.
Fixes issues with a couple of words in beta blog.
> docs: grammer update on beta annoucement

- website/docs/design/components/skeleton.md
Closes #862 
No current Skeleton design guidelines page.
Adds Skeleton design guidelines page.
> docs: added skeleton page

- website/docs/design/foundations/typography.md
Closes #871 
No current Typography design guidelines page.
Adds Typography design guidelines page.
This is definitely not the optimal experience for this page. The content requires and will be enhanced with visual examples and proper type styles in a fast follow. This allows these references to get out there while I move on for now. Will fast-follow with more polish soon.
> docs: added typography page

- website/src/css/custom.css
Docs using outdated unpkg imports
Updates to use jsdelivr
> docs: update unpkg links with jsdelivr

- website/docs/design/foundations/layout.md
Closes #881 
No current Layout/Grid/Alignment docs.
Adds Layout/Grid/Alignment design guidelines.
> docs: added layout page

- packages/design-tokens/styles/_typography.scss
closes #865 
- Updates typography styles based on new designs
- Updates sheet to use safer `:is()` pseudo selector
Makes typography more scalable by creating new `black-heading` and `<size>-code` classes.
> feat(tokens): update typography weights

- website/docs/development/headless-styles/Typography.mdx
- website/src/css/custom.css
- website/src/pages/index.js
Docs using old typography
Removes some strict overrides, while forcing new ones.
> docs: update typography styles & API

- website/src/components/Select/SelectSizes.preview.js
closes #883 
Updates HS > Select > Sizes preview to show label API
> docs: update SelectSizes preview

- packages/design-tokens/styles/themes.scss
closes #889 
Updates themes to use recommended Moz Dev docs hierarchy with prefers media selectors.
> fix(tokens): update themes.scss

- .codesandbox/ci.json
- packages/design-tokens/styles/themes.scss
Media "prefers" tags are still overriding the additional theme selectors due to heirarchy.
Removes media tags since they restrict tokens to only 2 themes.
> fix(tokens): remove prefers media tags

- website/src/css/custom.css
jsdelivr links are cached in an old state.
Updates custom.css to use latest next hard version to strictly enforce update.
> docs: use non-cached jsdelivr normalize url

- website/docs/design/foundations/forms.md
Closes #907 
No current Forms design guidelines page.
Adds Forms design guidelines page.
> docs: add forms page

- packages/headless-styles/sandbox/src/components/FormLabel.jsx
- packages/headless-styles/src/components/FormLabel/chakraFormLabel.ts
- packages/headless-styles/src/components/FormLabel/formLabelCSS.module.css
- packages/headless-styles/src/components/FormLabel/formLabelCSS.ts
- packages/headless-styles/src/components/FormLabel/formLabelJS.ts
- packages/headless-styles/src/components/FormLabel/generated/formLabelCSS.module.ts
- packages/headless-styles/src/components/FormLabel/shared.ts
- packages/headless-styles/src/components/FormLabel/types.ts
- packages/headless-styles/tests/formLabel/formLabelCSS.test.ts
- packages/headless-styles/tests/formLabel/formLabelJS.test.ts
contributes to #932 
Adds kind option for selecting visibility of form label
> feat(headless-styles): add kind option to form label

- website/docs/development/headless-styles/FormControl.mdx
closes #933 
Updates form label documentation to include the new option
> docs(headless-styles): add new kind option for form label docs

- .codesandbox/ci.json
HS was removed in ci.json because CS stalled out due to using Rollup.
Adds it back in with now unnecessary sandbox templates removed to see if it builds now.
> ci: update ci.json

- website/versioned_docs/version-0.3.1-beta/design/components/form-control.md
Lists "optional flag" in anatomy list.
Removes this list item.
> Removed optional flag from component anatomy list

- README.md
contributes #955 
Updates README social banner.
> chore: update README banner

- .github/CODEOWNERS
- .prettierignore
codeowners file was altered by prettier.
Added new teams and updated file using teams vs individual members.
> chore: update CODEOWNERS file

- packages/design-tokens/package.json
- packages/headless-styles/package.json
- packages/icons/package.json
- packages/react-utils/package.json
- packages/shared/package.json
- website/package.json
closes #984 
Updates all package meta to include correct Yarn versions
> chore: update workspace packageManager to match current version used

- website/docs/development/headless-styles/Checkbox.mdx
Checkbox page missing info in the Props section
Adds `iconOptions` to the information.
> docs: add missing Props iconOptions property

- website/src/components/Table/BasicTable.preview.js
closes #1005 
Adds correct syntax for Basic Table initial preview.
> docs: fix Basic Table initial preview

- website/README.md
closes #1020 
Updates website README to provide better information for contributors.
> docs(website): update README.md

- packages/headless-styles/index.experimental.js
- packages/headless-styles/index.stable.js
contributes to #1013 
Promotes select option APIs to `next`
> feat(headless-styles): promote select option APIs to next

- packages/headless-styles/src/components/Tooltip/generated/tooltipCSS.module.ts
- packages/headless-styles/src/components/Tooltip/shared.ts
- packages/headless-styles/src/components/Tooltip/tooltipCSS.module.css
- packages/headless-styles/src/components/shared/generated/tooltip.module.ts
- packages/headless-styles/src/components/shared/tooltip.module.css
- packages/headless-styles/tests/tooltip/tooltipCSS.test.ts
- packages/headless-styles/tests/tooltip/tooltipJS.test.ts
contributes #1001 
- Updates Tooltip to use disabled
- Updates shared tooltip styles to use correct class name
> refactor(headless-styles): update Tooltip to use disabled

- packages/design-tokens/styles/_core.scss
closes #1028 
Adds scrollbar styles to Normalize
> feat(design-tokens): add scrollbar styles to _core.scss

- .codesandbox/ci.json
- README.md
CS not running due to possible webhook trigger issues.
Testing update to see if it's fixed.
> docs: update README.md to test CS integration

- packages/design-tokens/utils/platforms/web.cjs
closes #1054 
Updates tokens to set class selector of `.pando-<theme>`
> feat(design-tokens): update class to use pando-<theme> selector

- website/docs/development/tokens/colors.mdx
closes #1056 
Updates theme page with latest API information
> docs: update colors.mdx themes section

- packages/headless-styles/sandbox/plugins/css-to-ts/convert-rules/standard.js
- packages/headless-styles/sandbox/src/components/Tabs.jsx
- packages/headless-styles/src/components/Avatar/generated/avatarCSS.module.ts
- packages/headless-styles/src/components/Checkbox/chakraCheckbox.ts
- packages/headless-styles/src/components/Checkbox/checkboxJS.ts
- packages/headless-styles/src/components/Checkbox/generated/checkboxCSS.module.ts
- packages/headless-styles/src/components/ConfirmDialog/generated/confirmDialogCSS.module.ts
- packages/headless-styles/src/components/Input/chakraInput.ts
- packages/headless-styles/src/components/Input/generated/inputCSS.module.ts
- packages/headless-styles/src/components/Menu/generated/menuCSS.module.ts
- packages/headless-styles/src/components/Popover/generated/popoverCSS.module.ts
- packages/headless-styles/src/components/Radio/chakraRadio.ts
- packages/headless-styles/src/components/Radio/generated/radioCSS.module.ts
- packages/headless-styles/src/components/Radio/radioJS.ts
- packages/headless-styles/src/components/Select/chakraSelect.ts
- packages/headless-styles/src/components/Switch/chakraSwitch.ts
- packages/headless-styles/src/components/Switch/generated/switchCSS.module.ts
- packages/headless-styles/src/components/Tabs/generated/tabsCSS.module.ts
- packages/headless-styles/src/components/Tabs/tabsJS.ts
- packages/headless-styles/src/components/Tag/generated/tagCSS.module.ts
- packages/headless-styles/src/components/TextLink/generated/textLinkCSS.module.ts
- packages/headless-styles/src/components/Textarea/chakraTextarea.ts
- packages/headless-styles/src/components/shared/generated/input.module.ts
- packages/headless-styles/src/components/shared/generated/states.module.ts
- packages/headless-styles/src/components/shared/generated/tooltip.module.ts
- packages/headless-styles/src/utils/helpers.ts
Reverts pluralsight/pando#1059
closes #1001
> Revert "Fix/1001 camelcase warnings"

- website/docs/development/react-utils/useTheme.mdx
closes #1015 
Adds useTheme API page in React utils section
> docs: add useTheme api page

- .vscode/extensions.json
- .vscode/tasks.json
> Add VsCode lint tasks, update recommended extensions

- packages/headless-styles/sandbox/plugins/css-to-ts/convert-rules/standard.js
- packages/headless-styles/sandbox/plugins/css-to-ts/utils/sanitize.js
- packages/headless-styles/src/components/Tabs/generated/tabsCSS.module.ts
- packages/headless-styles/src/components/shared/generated/tooltip.module.ts
> fix: sanitize whitespace in generated css ts output

- versions.mjs
Versions using RC info
Updates to prep for latest RC release.
> build: update versions.mjs for rc release

- website/docs/development/headless-styles/Typography.mdx
- website/versioned_docs/version-0.4.0-rc/development/headless-styles/Typography.mdx
closes #1105 
Adds the missing APIs
> docs: add display api information

- website/docs/development/headless-styles/Typography.mdx
Typo ("they" instead of "the")
Typo is corrected
> docs: fix typo in typography

- website/docs/development/headless-styles/FormControl.mdx
- website/src/theme/ReactLiveScope/index.js
closes #932 
Adds example of hidden label
> docs(headless-styles): add hidden label example

- packages/design-tokens/styles/_typography.scss
closes #1110 
Updates all CSS using FW to also include FVS
> fix(design-tokens): add missing fvs props in _typography.scss

- versions.mjs
Versions outdated
Updates to use new patch for latest
> build: update versions to 0.4.1

- website/blog/2023-02-16-dev-rc/index.md
- website/src/css/custom.css
closes #1103 
Adds new RC release blog
> docs(blog): add RC announcement

- packages/headless-styles/src/components/Tooltip/generated/tooltipCSS.module.ts
- packages/headless-styles/src/components/Tooltip/tooltipCSS.module.css
closes #1148 
Allows tooltip content to expand to max-content size up to 300px
> fix(headles-styles): allow tooltip content to expand up to 300px

- packages/headless-styles/src/components/Admonition/shared.ts
- packages/headless-styles/src/components/Avatar/shared.ts
- packages/headless-styles/src/components/Badge/shared.ts
- packages/headless-styles/src/components/Button/shared.ts
- packages/headless-styles/src/components/Checkbox/shared.ts
- packages/headless-styles/src/components/ConfirmDialog/shared.ts
- packages/headless-styles/src/components/ErrorMessage/shared.ts
- packages/headless-styles/src/components/IconButton/shared.ts
- packages/headless-styles/src/components/Input/shared.ts
- packages/headless-styles/src/components/Input/types.ts
- packages/headless-styles/src/components/Menu/shared.ts
- packages/headless-styles/src/components/Modal/shared.ts
- packages/headless-styles/src/components/Pagination/shared.ts
- packages/headless-styles/src/components/Popover/shared.ts
- packages/headless-styles/src/components/Progress/shared.ts
- packages/headless-styles/src/components/Progress/types.ts
- packages/headless-styles/src/components/Select/shared.ts
- packages/headless-styles/src/components/Select/types.ts
- packages/headless-styles/src/components/Tag/shared.ts
- packages/headless-styles/src/components/TextLink/shared.ts
- packages/headless-styles/src/components/shared/defaultOptions.ts
- packages/headless-styles/tests/pagination/paginationCSS.test.ts
closes #901
closes #1169 
Updates Pando to use correct typings for React compatibility
Current SB: https://codesandbox.io/s/ps-react-typescript-forked-lk9w60?file=/src/ErrorMessage.tsx
> fix(hs): update getErrorMessageA11yProps to use const

- packages/headless-styles/sandbox/src/components/Button.jsx
- packages/headless-styles/sandbox/src/components/IconButton.jsx
- packages/headless-styles/src/components/Button/buttonCSS.module.css
- packages/headless-styles/src/components/Button/buttonJS.ts
- packages/headless-styles/src/components/Button/generated/buttonCSS.module.ts
- packages/headless-styles/src/components/IconButton/generated/iconButtonCSS.module.ts
- packages/headless-styles/src/components/IconButton/iconButtonCSS.module.css
closes #1082 
closes #1122 
Updates Button & IconButton APIs to use interchangeable options.
https://codesandbox.io/s/ps-react-typescript-forked-3m6xq1?file=/src/App.tsx
> feat(hs): allow Btns to use any combination of sentiment/usage

- packages/headless-styles/src/components/IconButton/generated/iconButtonCSS.module.ts
- packages/headless-styles/src/components/IconButton/iconButtonCSS.module.css
IconButtons added borders which it doesn't need.
Removes them from styles.
https://codesandbox.io/s/ps-react-typescript-forked-gv178w?file=/src/App.tsx
> fix(hs): kill added border to icon button styles

- website/docs/learn/learn-pando/design-patterns/entering-dates.mdx
- website/versioned_docs/version-0.4.1/learn/learn-pando/design-patterns/entering-dates.mdx
Add design pattern page for date input
> docs: add design pattern for date entry

- packages/headless-styles/sandbox/src/components/Avatar.jsx
- packages/headless-styles/src/components/Button/buttonCSS.module.css
- packages/headless-styles/src/components/Button/generated/buttonCSS.module.ts
closes #1120 
- Updates Avatar sandbox to validate Button focusing works as intended.
- Fixes Button text bug
https://codesandbox.io/s/ps-react-typescript-forked-25kflj?file=/src/App.tsx
> 1120 feature avatar should support button usage

- website/docs/learn/about-pando/versioning.md
relates to #1185
Makes Pando branding changes proposed by Tim to 'next' version of versioning docs
> docs: update Pando branding in versioning.md

- website/docs/learn/about-pando/a11y.md
Typo in Accessibility page title
Fixes the typo.
> fix(nav): a11y page title typo

- website/docs/learn/learn-pando/design-patterns/pagination.mdx
- website/versioned_docs/version-0.4.1/learn/learn-pando/design-patterns/pagination.mdx
adds pagination design pattern page
> docs: add pagination design pattern page

- packages/headless-styles/index.experimental.js
- packages/headless-styles/index.stable.js
- packages/headless-styles/sandbox/src/components/Badge.jsx
- packages/headless-styles/src/components/Badge/badgeCSS.module.css
- packages/headless-styles/src/components/Badge/badgeCSS.ts
- packages/headless-styles/src/components/Badge/badgeJS.ts
- packages/headless-styles/src/components/Badge/generated/badgeCSS.module.ts
- packages/headless-styles/src/components/Badge/shared.ts
- packages/headless-styles/src/components/Badge/types.ts
- packages/headless-styles/src/components/Button/buttonCSS.ts
- packages/headless-styles/src/components/Button/shared.ts
- packages/headless-styles/src/index.ts
- packages/headless-styles/src/utils/types.ts
- packages/headless-styles/tests/badge/badgeCSS.test.ts
- packages/headless-styles/tests/badge/badgeJS.test.ts
- packages/headless-styles/tests/button/buttonCSS.test.ts
- Adds classNames option to Badge API
- Makes Badge APIs composable
https://codesandbox.io/s/ps-react-typescript-forked-olsptt?file=/src/App.tsx
> refactor(hs): update Badge API to include classNames & composability

- packages/headless-styles/src/components/Grid/gridCSS.ts
- packages/headless-styles/src/components/Grid/shared.ts
- packages/headless-styles/src/components/Grid/types.ts
- packages/headless-styles/tests/grid/gridCSS.test.ts
Updates Grid APIs to add classNames option
https://codesandbox.io/s/ps-react-typescript-forked-h5ugsj?file=/src/App.tsx
> feat(hs): update Grid to accept classNames

- packages/headless-styles/src/components/IconButton/iconButtonCSS.ts
- packages/headless-styles/src/components/IconButton/shared.ts
- packages/headless-styles/src/components/IconButton/types.ts
- packages/headless-styles/tests/iconButton/iconButtonCSS.test.ts
Updates IconButton API to accept classNames option
https://codesandbox.io/s/ps-react-typescript-forked-36p2wh?file=/src/App.tsx
> feat(hs): add IconButton classNames option

- packages/headless-styles/src/components/Tag/shared.ts
- packages/headless-styles/src/components/Tag/tagCSS.ts
- packages/headless-styles/src/components/Tag/types.ts
- packages/headless-styles/tests/tag/tagCSS.test.ts
Updates Tag API to include classNames option
https://codesandbox.io/s/ps-react-typescript-forked-crw36s?file=/src/App.tsx
> feat(hs): update Tag API to include classNames option

- packages/headless-styles/src/components/Textarea/shared.ts
- packages/headless-styles/src/components/Textarea/textareaCSS.ts
- packages/headless-styles/src/components/Textarea/types.ts
- packages/headless-styles/tests/textarea/textareaCSS.test.ts
Updates Textarea to accept classNames option
https://codesandbox.io/s/ps-react-typescript-forked-tt4kyk?file=/src/App.tsx
> feat(hs): update Textarea to accept classNames prop

- website/docs/reference/components/pagination.mdx
Corresponding fix for a typo noted by a contributor in the versioned docs
> docs: correct typo in accessibility heading

- scripts/release/publish.js
closes #1254 
Adds filtering to packages list being sent to validation helpers
> fix: add package filtering in publish.js based on Node env

- packages/react/index.experimental.js
- packages/react/index.stable.js
- packages/react/src/components/Button.tsx
- packages/react/src/index.ts
- packages/react/tests/components/button.test.tsx
- packages/sandbox/src/App.tsx
- packages/sandbox/src/components/ButtonPage.tsx
closes #1275 
Adds Button component to react lib
https://codesandbox.io/s/ps-react-typescript-forked-9z2dt7?file=/src/App.tsx
> feat: 1275 feature add button component

- jest.config.cjs
- packages/headless-styles/index.experimental.js
- packages/headless-styles/index.stable.js
- packages/headless-styles/src/components/Table/shared.ts
- packages/headless-styles/src/components/Table/tableCSS.ts
- packages/headless-styles/src/components/Table/tableJS.ts
- packages/headless-styles/src/index.ts
- packages/headless-styles/tests/table/tableCSS.test.ts
- packages/headless-styles/tests/table/tableJS.test.ts
contributes #1320 
Updates HS Table API to be composable for React lib
https://codesandbox.io/s/ps-react-typescript-forked-nrcsfs?file=/src/App.tsx
> feat(hs): update Table API to be composable

- packages/headless-styles/src/components/TextLink/shared.ts
- packages/headless-styles/src/components/TextLink/textLinkCSS.ts
- packages/headless-styles/src/components/TextLink/types.ts
- packages/headless-styles/tests/textLink/textLinkCSS.test.ts
contributes to #1360 
Updates the TextLink API to extend DefaultOptions and integrate with React better
https://codesandbox.io/s/ps-react-typescript-forked-61moqr?file=/src/App.tsx
> feat(hs): update TextLink to extend DefaultOptions

- packages/headless-styles/src/components/Grid/shared.ts
contributes #1387
Updates grid styles to be strictly typed for better component integration
https://codesandbox.io/s/ps-react-typescript-forked-83rrze?file=/src/App.tsx
> fix(hs): add CSSProperties type to grid helpers

- packages/headless-styles/src/components/Grid/shared.ts
- packages/headless-styles/tests/grid/gridCSS.test.ts
closes #1409 
Updates GTA to use inline style required formatting.
https://codesandbox.io/s/ps-react-typescript-forked-b64r96?file=/src/App.tsx
> fix(hs): update getFormattedAreas to use correct formatting

- packages/headless-styles/src/components/ErrorMessage/errorMessageCSS.ts
- packages/headless-styles/src/components/ErrorMessage/shared.ts
- packages/headless-styles/src/components/ErrorMessage/types.ts
- packages/headless-styles/src/components/FieldMessage/fieldMessageCSS.ts
- packages/headless-styles/src/components/FieldMessage/shared.ts
- packages/headless-styles/src/components/FieldMessage/types.ts
- packages/headless-styles/src/components/shared/defaultOptions.ts
- packages/headless-styles/src/components/types.ts
- packages/headless-styles/tests/errorMessage/errorMessageCSS.test.ts
- packages/headless-styles/tests/fieldMessage/fieldMessageCSS.test.ts
closes #1419 
Updates fieldMessages HS API for better component usage
https://codesandbox.io/s/ps-react-typescript-forked-4pnq4c?file=/src/App.tsx
> refactor(hs): update fieldMessages to for better component integration

- packages/react/index.experimental.js
- packages/react/index.stable.js
- packages/react/src/components/Show.tsx
- packages/react/src/index.ts
- packages/react/tests/components/show.test.tsx
- packages/sandbox/src/components/FormsPage.tsx
closes #1435 
Adds new Show component to React lib
https://codesandbox.io/s/ps-react-typescript-forked-w976vd?file=/src/App.tsx
> 1435 feature make show component

- packages/headless-styles/index.experimental.js
- packages/headless-styles/index.stable.js
- packages/headless-styles/src/components/Input/inputCSS.ts
- packages/headless-styles/src/components/Input/shared.ts
- packages/headless-styles/src/components/Input/types.ts
- packages/headless-styles/src/components/Pagination/shared.ts
- packages/headless-styles/src/components/Select/selectCSS.ts
- packages/headless-styles/src/components/Select/shared.ts
- packages/headless-styles/src/components/Select/types.ts
- packages/headless-styles/src/components/Textarea/shared.ts
- packages/headless-styles/src/components/Textarea/textareaCSS.ts
- packages/headless-styles/src/components/Textarea/types.ts
- packages/headless-styles/src/components/shared/defaultOptions.ts
- packages/headless-styles/src/components/shared/helpers/input.ts
- packages/headless-styles/src/components/shared/types/input.types.ts
- packages/headless-styles/src/index.ts
- packages/headless-styles/tests/input/inputCSS.test.ts
- packages/headless-styles/tests/pagination/paginationCSS.test.ts
- packages/headless-styles/tests/select/selectCSS.test.ts
- packages/headless-styles/tests/textarea/textareaCSS.test.ts
closes #1440 
Updates Input HS API to be composable for better component integration
https://codesandbox.io/s/ps-react-typescript-forked-ovhlzl?file=/src/App.tsx
> 1446 feature refactor hs input code

- .pnp.cjs
- packages/react-utils/package.json
- packages/react/package.json
- packages/sandbox/src/components/AdmonitionPage.tsx
- packages/sandbox/src/components/AvatarPage.tsx
- packages/sandbox/src/components/BadgePage.tsx
- packages/sandbox/src/components/ButtonPage.tsx
- packages/sandbox/src/components/CircularProgress.tsx
- packages/sandbox/src/components/FormsPage.tsx
- packages/sandbox/src/components/GridPage.tsx
- packages/sandbox/src/components/IconButtonPage.tsx
- packages/sandbox/src/components/IconPage.tsx
- packages/sandbox/src/components/ProgressBarPage.tsx
- packages/sandbox/src/components/SkeletonPage.tsx
- packages/sandbox/src/components/TablePage.tsx
- packages/sandbox/src/components/TagPage.tsx
- packages/sandbox/src/components/TextLinkPage.tsx
- yarn.lock
closes #1458 
- Updates React to include dev/prod package settings
- - Updates React-utils to include dev/prod package settings
https://codesandbox.io/s/ps-react-typescript-forked-w1z0gt?file=/src/App.tsx
> 1458 feature update react to use publishconfig settings

- packages/headless-styles/package.json
- packages/react-utils/package.json
- packages/react/package.json
closes #1460 
Relocates `files` prop in package.json to be in global scope and only include prod files.
> fix: update HS/R/RU to remove files from publishConfig

- packages/headless-styles/index.experimental.js
- packages/headless-styles/index.stable.js
contributes #1460 
Removes exports to non-existing APIs in HS
> 1460 bug builds are missing files

- packages/react/.eslintrc.cjs
- packages/react/index.experimental.js
- packages/react/index.stable.js
- packages/react/src/components/Input.tsx
- packages/react/src/components/Textarea.tsx
- packages/react/src/index.ts
- packages/react/tests/components/textarea.test.tsx
- packages/sandbox/src/components/FormsPage.tsx
closes #1464 
Adds Textarea to React lib & sandbox
> 1464 feature create textarea component

- packages/headless-styles/src/components/Checkbox/checkboxCSS.scss
- packages/headless-styles/src/components/Checkbox/checkboxCSS.ts
- packages/headless-styles/src/components/Checkbox/shared.ts
- packages/headless-styles/src/components/Checkbox/types.ts
- packages/headless-styles/src/components/Radio/types.ts
- packages/headless-styles/src/components/Switch/types.ts
- packages/headless-styles/src/components/shared/_input.scss
- packages/headless-styles/src/components/shared/defaultOptions.ts
- packages/headless-styles/src/components/shared/helpers/input.ts
- packages/headless-styles/src/components/shared/types/input.types.ts
- packages/headless-styles/tests/checkbox/checkboxCSS.test.ts
- packages/react/index.experimental.js
- packages/react/index.stable.js
- packages/react/src/components/Checkbox.tsx
- packages/react/src/index.ts
- packages/react/tests/components/checkbox.test.tsx
- packages/sandbox/src/components/FormsPage.tsx
closes #1480 
- Updates HS Checkbox API to use new shared Input helpers
> refactor(hs): update checkbox to use new shared input helpers

- packages/headless-styles/src/components/Input/shared.ts
- packages/headless-styles/tests/input/inputCSS.test.ts
- packages/react-utils/index.experimental.js
- packages/react-utils/index.stable.js
- packages/react/index.experimental.js
- packages/react/index.stable.js
- packages/react/src/components/Checkbox.tsx
- packages/react/src/components/IconButton.tsx
- packages/react/src/index.ts
- packages/react/tests/components/checkbox.test.tsx
- packages/sandbox/src/components/FormsPage.tsx
closes #1484 
- Updates minor bugs in input-related HS APIs
- Adds Indeterminate Icon for Checkbox component
> 1484 bug add missing indeterminate icon to checkbox

- packages/headless-styles/src/components/Radio/radioCSS.ts
- packages/headless-styles/src/components/Radio/shared.ts
- packages/headless-styles/src/components/Radio/types.ts
- packages/headless-styles/tests/radio/radioCSS.test.ts
- packages/react/index.experimental.js
- packages/react/index.stable.js
- packages/react/src/components/Checkbox.tsx
- packages/react/src/components/Radio.tsx
- packages/react/src/index.ts
- packages/react/tests/components/radio.test.tsx
- packages/sandbox/src/components/FormsPage.tsx
> refactor(hs): update radioCSS.ts

- packages/headless-styles/index.experimental.js
- packages/headless-styles/index.stable.js
- packages/headless-styles/src/components/Switch/shared.ts
- packages/headless-styles/src/components/Switch/switchCSS.ts
- packages/headless-styles/src/components/Switch/types.ts
- packages/headless-styles/src/index.ts
- packages/headless-styles/tests/switch/switchCSS.test.ts
- packages/react/index.experimental.js
- packages/react/index.stable.js
- packages/react/src/components/Toggle.tsx
- packages/react/src/index.ts
- packages/react/tests/components/toggle.test.tsx
- packages/sandbox/src/components/FormsPage.tsx
contributes #1497
- compose switch wrapper props in HS
- make Toggle/Button component
> feat(react): make Toggle.tsx

- packages/headless-styles/index.experimental.js
- packages/headless-styles/index.stable.js
- packages/headless-styles/src/components/Switch/shared.ts
- packages/headless-styles/src/components/Switch/switchCSS.ts
- packages/headless-styles/src/components/Switch/types.ts
- packages/headless-styles/src/components/shared/defaultOptions.ts
- packages/headless-styles/src/index.ts
- packages/headless-styles/tests/switch/switchCSS.test.ts
- packages/react/index.experimental.js
- packages/react/index.stable.js
- packages/react/src/components/Toggle.tsx
- packages/react/src/index.ts
- packages/react/tests/components/toggle.test.tsx
- packages/sandbox/src/components/FormsPage.tsx
closes #1497
Refactors switch API to use shared helpers
> refactor(hs): update switchCSS to use new input helpers

- packages/react/index.experimental.js
- packages/react/index.stable.js
- packages/react/src/components/Portal.tsx
- packages/react/src/index.ts
- packages/react/tests/components/portal.test.tsx
closes #1502 
Adds Portal to React lib
> feat(react): create Portal.tsx

- packages/headless-styles/src/components/Pagination/shared.ts
- packages/headless-styles/src/components/Select/shared.ts
- packages/headless-styles/tests/pagination/paginationCSS.test.ts
- packages/headless-styles/tests/select/selectCSS.test.ts
- packages/react/index.experimental.js
- packages/react/index.stable.js
- packages/react/src/components/Select.tsx
- packages/react/src/index.ts
- packages/react/tests/components/select.test.tsx
- packages/sandbox/src/components/FormsPage.tsx
> feat(react): add Select.tsx

- packages/headless-styles/src/components/Pagination/shared.ts
- packages/headless-styles/src/components/Select/selectCSS.ts
- packages/headless-styles/src/components/Select/shared.ts
- packages/headless-styles/src/components/Select/types.ts
- packages/headless-styles/tests/pagination/paginationCSS.test.ts
- packages/headless-styles/tests/select/selectCSS.test.ts
- packages/react/index.experimental.js
- packages/react/index.stable.js
- packages/react/src/components/Select.tsx
- packages/react/src/index.ts
- packages/react/tests/components/select.test.tsx
- packages/sandbox/src/components/FormsPage.tsx
closes #1506 
Updates HS Select API to compliment React lib.
>  feat: 1506 hs select STACK: 1 of 2

- packages/react/src/context/Toast/context.tsx
- packages/react/tests/context/toastProvider.test.tsx
closes #1517 
- Adds missing text className
- Makes undo button conditional
> fix(react): make onAction conditional in context.tsx

- .github/workflows/alt_bot.yml
There's no validation to the repo when people post images without alt text.
Adds new GH Alt Bot to validate that so everyone can participate in the conversations.
> ci: add GH alt bot workflow

- packages/react/src/components/AlertDialog/actions.tsx
- packages/react/src/context/Confirm/context.tsx
- packages/react/src/context/Confirm/types.ts
- packages/react/tests/context/confirmProvider.test.tsx
- packages/sandbox/src/components/ConfirmPage.tsx
closes #1530 
Updates ConfirmProvider to use more desired behavior to match the docs.
> refactor(react): update ConfirmProvider to export confirm function

- packages/react/src/context/Confirm/context.tsx
- packages/react/src/context/Prompt/context.tsx
- packages/react/src/context/shared/alert.hooks.ts
- packages/react/src/context/shared/alert.types.ts
- website/docs/reference/components/confirm-dialog.mdx
- website/docs/reference/components/prompt-dialog.mdx
closes #1536 
Updates the Alert component APIs to use conditional props vs required for a cleaner UX.
> 1536 feature update alert apis to use default bodyheading ids

- packages/design-tokens/package.json
normalize.css is now able to be imported from the design-tokens library which allows for another option other than the cdn
> feat(design-tokens): add normalize.css to exports

- .github/workflows/dependabot_dep_install.yml
DB workflow needs some fine tuning for pushing changes
Updates checkout to use `fetch-depth` and `push` settings
> ci: update dependabot_dep_install.yml

- .github/workflows/publish_experimental_release.yml
- .github/workflows/publish_next_release.yml
- .github/workflows/publish_stable_releases.yml
- packages/design-tokens/package.json
- packages/headless-styles/package.json
- packages/icons/package.json
- packages/react-utils/package.json
- packages/react/package.json
NPM not publishing packages post token update
Changes some settings to match current NPM docs
> ci: update NPM token strategy

- .github/workflows/publish_experimental_release.yml
- .github/workflows/publish_next_release.yml
- .github/workflows/publish_stable_releases.yml
Yarn auth token not being used
Adds it back in to all publish workflows
> chore: update yarn config with npmAuthToken

- scripts/release/publish-commands/publish-to-npm.mjs
Npm not publishing packages
Updates logic in publish file
> ci: update publish-to-npm.mjs

- website/blog/2023-07-18-dev-beta-2/index.md
closes #1597 
Adds new blog announcing latest release
> docs: create new blog

- scripts/release/publish-commands/check-npm-permissions.mjs
New packages fail to publish in the CI
Updates the info call to use try/catch and allow new packages for PS user
> ci: update check-npm-permissions to allow new packages

- .codesandbox/ci.json
- .pnp.cjs
- jest.config.cjs
- packages/react-aria/index.experimental.js
- packages/react-aria/index.stable.js
- packages/react-aria/package.json
- packages/react-aria/rollup.config.mjs
- packages/react-aria/src/index.ts
- packages/react-aria/src/tabs.ts
- packages/react-aria/tests/a11y-tabs.test.tsx
- packages/react-aria/tsconfig.json
- packages/react/package.json
- yarn.lock
closes #1605 
Adds new React-aria tabs hooks & types to package
> 1605 feature create tabs a11y helpers

- packages/headless-styles/src/components/Tabs/tabs.scss
- packages/headless-styles/src/components/Tabs/tabs.ts
- packages/react-aria/src/tabs.ts
- packages/react-aria/tests/a11y-tabs.test.tsx
- packages/react/src/components/tabs.tsx
- packages/react/tests/components/tabs.test.tsx
- packages/sandbox/src/components/TabsPage.tsx
closes #1609 
- Adds JSDOC notes in HS
- Adds disabled style to HS tab helper
- Adds aria hooks to React Tab components
- Fine tune aria hooks where needed
> 1609 feature use aria hooks in tab components

- packages/react-aria/src/helpers/keyDown.ts
- packages/react-aria/src/helpers/types.ts
- packages/react-aria/src/index.ts
- packages/react-aria/src/shared/const.ts
- packages/react-aria/src/tabs.ts
- packages/react-aria/tests/a11y-tabs.test.tsx
- packages/react-aria/tests/helpers/keyDown.test.ts
- packages/react-aria/tests/shared/const.test.ts
- packages/react/src/components/tabs.tsx
- packages/react/src/context/TabsContext.tsx
- packages/react/tests/components/tabs.test.tsx
closes #1618 
Adds keyboard navigation for Tabs aria hooks
> 1618 feature add tabs a11y keyboard event hook

- packages/headless-styles/types.tsconfig.json
- packages/react/tsconfig.build.json
JSDOC comments are being stripped out when building type definitions
Updates the TS build to keep comments in so they are used in TS environments
> chore: update tsconfig.build.json in HS and React

- .github/workflows/publish_experimental_release.yml
- .github/workflows/publish_next_release.yml
- .github/workflows/publish_stable_releases.yml
Publish workflows failing due to NPM permissions
Updates publish workflows to use pnpm recommended approach
> ci: update publish workflows

- .github/workflows/publish_experimental_release.yml
- .github/workflows/publish_next_release.yml
- .github/workflows/publish_stable_releases.yml
NPM auth failing in CI
Updates workflows to use [this strategy](https://github.com/pnpm/pnpm/issues/3141#issuecomment-1305563972)
> ci: update releases.yml

- scripts/release/publish-commands/publish-to-npm.mjs
> ci: remove tolerate-republish in publish-to-npm.mjs

- scripts/release/publish-commands/publish-to-npm.mjs
Publishing failing due to some updates we need to make to pnpm publish command
Updates the flags
> ci: update pnpm publish flags

- scripts/release/publish-commands/publish-to-npm.mjs
NPM tag command is no longer supported
Updates to use the now `dist-tag` version
> ci: use dist-tag cmd

- .github/workflows/linting.yml
- .gitignore
- jest.config.cjs
- package.json
- packages/design-tokens/build-mobile/compose/StyleDictionaryColor.kt
- packages/design-tokens/package.json
- packages/headless-styles/package.json
- packages/icons/package.json
- packages/react-aria/package.json
- packages/react-utils/package.json
- packages/react/package.json
- packages/shared/package.json
- pnpm-lock.yaml
- turbo.json
closes #1677 
Adds turbo and update ci/scripts to use it
> 1677 feature add turbo

- packages/design-tokens/tokens/base/action.yaml
closes #1645 
Updates `action-bg-weak` values to match new design standards
> refactor(tokens): update action-bg values

- packages/design-tokens/styles/_tooltip.scss
closes #1685 
Fine tunes the styles for the top position
> fix: fine tune styles in _tooltip.scss

- packages/design-tokens/styles/_tooltip.scss
There is no way to opt-out of the tooltip
Adds feature via the `data-hide-tooltip` attr.
> feat(tokens): add ability to hide tooltip

- packages/design-tokens/styles/_tooltip.scss
tooltip hide selector not being used.
Updates the selector to use the strict `="true"` value.
> fix(normalize): use strict selector for data-hide-tooltip

- package.json
- website/package.json
Website not deploying due to pnpm confusion
Updates website scripts to not use reserved `deploy` pnpm command
> ci: update website to not use deploy pnpm reserved script

- packages/design-tokens/styles/_tooltip.scss
closes #1692 
Updates the tooltip to show the `aria-label` contents when `data-tooltip` exists.
> refactor(tokens): update _tooltip.scss to use data-tooltip

- versions.mjs
> chore: update versions.mjs

- .github/workflows/publish_stable_releases.yml
Stable build failing due to missing node modules
Adds install command to job
> ci: add install cmd to publish_stable_releases.yml

- website/blog/2023-09-07-dev-0.7.1/index.md
> docs: add 0.7.1 blog

- packages/panda-preset/README.md
- packages/panda-preset/package.json
- packages/panda-preset/src/globalCss.ts
- packages/panda-preset/src/index.ts
- packages/panda-preset/src/patterns.ts
- packages/panda-preset/src/types.ts
- packages/panda-preset/src/utilities.ts
- pnpm-lock.yaml
closes #1716 
Adds initial panda-css config/preset settings
> 1716 feature initial panda css preset config

- packages/panda-preset/package.json
- packages/panda-preset/src/conditions.ts
- packages/panda-preset/src/index.ts
- packages/panda-preset/src/theme/index.ts
- packages/panda-preset/src/theme/textStyles.ts
- packages/panda-preset/src/theme/tokens.ts
- packages/panda-preset/src/utilities.ts
- packages/react/tsconfig.json
- packages/sandbox/.gitignore
- packages/sandbox/index.html
- packages/sandbox/package.json
- packages/sandbox/panda.config.ts
- packages/sandbox/postcss.config.cjs
- packages/sandbox/src/App.module.css
- packages/sandbox/src/App.tsx
- packages/sandbox/src/components/ActionMenuPage.tsx
- packages/sandbox/src/main.tsx
- packages/sandbox/src/pando.entry.css
- packages/sandbox/tsconfig.json
- packages/sandbox/vite.config.ts
- pnpm-lock.yaml
closes #1719 
Updates sandbox to use PandaCSS with Pando preset for development
> feat(sandbox): add Panda w/ Pando Preset

- packages/panda-preset/src/globalCss.ts
- packages/panda-preset/src/theme/textStyles.ts
- packages/sandbox/index.html
- packages/sandbox/src/App.tsx
closes #1722 
Updates preset to use Pando textStyles
> 1722 feature add textstyles to preset

- packages/headless-styles/src/index.ts
Export styles from headless-styles
Added a missing export to the headless-styles package so that style objects are being exported again.
> CL-594: Export styles from headless-styles

- packages/panda-preset/src/conditions.ts
- packages/panda-preset/src/globalCss.ts
- packages/panda-preset/src/index.ts
- packages/panda-preset/src/theme/index.ts
- packages/panda-preset/src/theme/semantic-tokens/index.ts
- packages/panda-preset/src/theme/semantic-tokens/neutral.ts
- packages/panda-preset/src/theme/semantic-tokens/types.ts
- packages/panda-preset/src/types.ts
- packages/sandbox/src/App.tsx
closes #1636 
- Adds neutral tokens to preset
- Updates sandbox to use latest preset build
> 1636 feature update dt to produce objects that match the panda config

- jest.config.cjs
- packages/panda-preset/package.json
- packages/panda-preset/src/index.ts
- packages/panda-preset/src/theme/semantic-tokens/action.ts
- packages/panda-preset/src/theme/semantic-tokens/index.ts
- packages/panda-preset/tests/semanticTokens/action.test.ts
- packages/panda-preset/tests/semanticTokens/neutral.test.ts
- packages/panda-preset/tsconfig.build.json
- packages/panda-preset/tsconfig.cjs.json
- packages/panda-preset/tsconfig.json
closes #1729 
Adds action tokens to panda preset
> 1729 feature add action tokens to panda preset

- packages/panda-preset/src/index.ts
- packages/panda-preset/src/theme/semantic-tokens/action.ts
- packages/panda-preset/src/theme/semantic-tokens/index.ts
- packages/panda-preset/src/theme/semantic-tokens/info.ts
- packages/panda-preset/src/theme/semantic-tokens/neutral.ts
- packages/panda-preset/src/theme/semantic-tokens/types.ts
- packages/panda-preset/tests/semanticTokens/action.test.ts
- packages/panda-preset/tests/semanticTokens/info.test.ts
- packages/panda-preset/tests/semanticTokens/neutral.test.ts
closes #1730 
Adds info tokens to panda-preset
> 1730 feature move info tokens to preset

- packages/panda-preset/src/index.ts
- packages/panda-preset/src/theme/semantic-tokens/index.ts
- packages/panda-preset/src/theme/semantic-tokens/success.ts
- packages/panda-preset/tests/semanticTokens/success.test.ts
- packages/panda-preset/tsconfig.build.json
- packages/panda-preset/tsconfig.json
closes #1731 
Adds success tokens to panda preset
> feat(preset): add success tokens

- packages/panda-preset/src/index.ts
- packages/panda-preset/src/theme/semantic-tokens/index.ts
- packages/panda-preset/src/theme/semantic-tokens/warning.ts
- packages/panda-preset/tests/semanticTokens/warning.test.ts
closes #1732 
Adds warning tokens to panda-preset
> feat(preset): add warning tokens

- packages/panda-preset/src/index.ts
- packages/panda-preset/src/theme/semantic-tokens/danger.ts
- packages/panda-preset/src/theme/semantic-tokens/index.ts
- packages/panda-preset/tests/semanticTokens/danger.test.ts
closes #1733 
Adds danger tokens to panda-preset
> feat(preset): create danger tokens

- .github/dependabot.yml
- packages/panda-preset/src/conditions.ts
- packages/panda-preset/src/globalCss.ts
- packages/panda-preset/src/index.ts
- packages/panda-preset/src/theme/index.ts
- packages/panda-preset/src/theme/keyframes.ts
- packages/panda-preset/tests/keyframes.test.ts
closes #1740 
- Adds remaining globalCss styles
- Adds new conditions
- Adds keyframes
> 1740 feature add missing global styles

- .vscode/settings.json
- packages/panda-preset/src/globalCss.ts
- packages/sandbox/index.html
- packages/sandbox/package.json
- packages/sandbox/panda.config.ts
- packages/sandbox/src/App.tsx
- pnpm-lock.yaml
closes #1744 
Updates the sandbox to use the latest Pando panda-preset and tests it's ease of use
> 1744 feature update dev sandbox w latest panda preset

- .github/workflows/docs_build.yml
- .github/workflows/docs_release.yml
- bun/src/paths.mts
- bun/src/website/build.mts
- bun/src/website/clear.mts
- bun/src/website/deploy.mts
- bun/src/website/serve.mts
- bun/src/website/start.mts
- bun/tsconfig.json
- package.json
closes #1772 
- Refactors all website scripts to use Bun
- Updates GH Actions
> 1772 feature update website scripts to use bun

- .github/workflows/tests.yml
- .vscode/launch.json
- .vscode/settings.json
- bun/src/paths.mts
- bun/src/sandbox/start.mts
- package.json
- packages/design-tokens/package.json
- packages/headless-styles/package.json
- packages/icons/package.json
- packages/panda-preset/package.json
- packages/pando/package.json
- packages/react-aria/package.json
- packages/react-utils/package.json
- packages/react/package.json
- packages/shared/package.json
- scripts/release/build-commands/build-prerelease-packages.mjs
- scripts/release/publish-commands/publish-to-npm.mjs
- scripts/release/shared-commands/print-prerelease-summary.mjs
- website/package.json
closes #1784 
Updates scripts to use `npm` not `pnpm` for Bun compatibility.
> 1784 bug scripts are still using pnpm to publish internally

- packages/panda-preset/src/theme/tokens.ts
- packages/panda-preset/src/utilities.ts
> 1845 docs panda descriptions

- packages/react/src/components/Admonition.tsx
- packages/react/src/components/AlertDialog/actions.tsx
- packages/react/src/components/AlertDialog/text.tsx
- packages/react/src/components/Avatar.tsx
- packages/react/src/components/Button.tsx
- packages/react/src/components/Checkbox.tsx
- packages/react/src/components/ErrorMessage.tsx
- packages/react/src/components/FieldMessage.tsx
- packages/react/src/components/For.tsx
- packages/react/src/components/IconButton.tsx
- packages/react/src/components/Input.tsx
- packages/react/src/components/Menu/actions.tsx
- packages/react/src/components/Menu/sections.tsx
- packages/react/src/components/PopoverContent.tsx
- packages/react/src/components/Portal.tsx
- packages/react/src/components/Radio.tsx
- packages/react/src/components/Select.tsx
- packages/react/src/components/Toast.tsx
- packages/react/src/components/Toggle.tsx
- packages/react/src/components/tabs.tsx
closes #1852 
Adds client directives for v19 support
> feat(react): add client directives to client like components

- .github/workflows/publish_experimental_release.yml
- .github/workflows/publish_next_release.yml
- packages/design-tokens/README.md
- packages/headless-styles/README.md
> 1863 feature update workflows to archive build directory

- sandbox/app/components/AppBar.tsx
- sandbox/app/components/Console.tsx
- sandbox/app/components/Nav.tsx
- sandbox/app/page.tsx
- tests/__mocks__/styled-system/css/index.mjs
- tests/__mocks__/styled-system/patterns/index.mjs
- tests/sandbox/AppBar.test.tsx
- tests/sandbox/Console.test.tsx
- tests/sandbox/Nav.test.tsx
- tests/sandbox/page.test.tsx
> 1867 sandbox tests

- .github/workflows/publish_experimental_release.yml
- .github/workflows/publish_next_release.yml
> 1876 bug remove archive in ci

- sandbox/app/components/AppBar.tsx
- sandbox/app/components/Console.tsx
- sandbox/app/components/Nav.tsx
- sandbox/app/page.tsx
- tests/sandbox/AppBar.test.tsx
- tests/sandbox/Console.test.tsx
- tests/sandbox/Nav.test.tsx
- tests/sandbox/layout.test.tsx
- tests/sandbox/page.test.tsx
Closes #1880 
- removes data-testid from sandbox test
- standardizes whitespace within tests
> 1880 sandbox tests

- tests/__mocks__/moduleMock.ts
- tests/__mocks__/windowMatchMedia.mock.ts
- tests/sandbox/AppBar.test.tsx
- tests/sandbox/layout.test.tsx
an addition to pr #1888 which intros mocks that make most tests pass
There is still a test failing but it may be functionality related rather than mocking
> required mocks for hooks & matchMedia

- packages/panda-preset/src/index.ts
Preset was not shipping recipes and themes because the import path was not pointing to a direct file
Updates the paths to point specifically to the index file for directory
> fix: update preset to include file paths

- packages/panda-preset/src/index.ts
- packages/panda-preset/src/theme/index.ts
Same error but with deeply nested dir
Update paths to build successfully
> chore(preset): update file paths for nested dir

- packages/panda-preset/src/theme/semantic-tokens/neutral.ts
- tests/panda-preset/semanticTokens/neutral.test.ts
closes #1933 
Removes addition of deprecated naming in the neutral tokens
> refactor(preset): revert breaking neutral token changes

- packages/panda-preset/src/conditions.ts
- packages/panda-preset/src/index.ts
- packages/panda-preset/src/recipes/index.ts
- packages/panda-preset/src/recipes/input.ts
- sandbox/app/components/Nav.tsx
- sandbox/app/react/input/page.tsx
- tests/panda-preset/conditions.test.ts
- tests/sandbox/pages/inputPage.test.tsx
closes #1936 
- Adds input recipe
- Adds new `_userInvalid` condition
- Updates sandbox
- Adds initial sandbox tests
> 1936 feature add input recipe

- packages/panda-preset/src/recipes/button.ts
- packages/panda-preset/src/recipes/index.ts
- packages/panda-preset/src/recipes/label.ts
- sandbox/app/components/Nav.tsx
- sandbox/app/react/label/page.tsx
- tests/sandbox/pages/labelPage.test.tsx
closes #1949 
- Adds recipe
- Adds sandbox page
- Adds sandbox page tests
> feat(preset): create label recipe

- sandbox/app/globals.css
Sandbox was not using the Panda globals 🙈 
Adds it in
> fix: add layer order to globals.css

- docs/astro.config.mjs
- docs/src/components/DocumentStatus.tsx
- docs/src/content/docs/explanation/color.md
- docs/src/content/docs/reference/color/info-palette.mdx
Closes #1944
* Adds new info palette page (migrated over from [figma](https://www.figma.com/proto/uJtPfI38D9i8iQg0UGK2E0/Pando-Design-Guidelines?node-id=481-19105&starting-point-node-id=6%3A11626))
* Adds navigation to info palette page
> 1944 feat info palette

- docs/astro.config.mjs
- docs/src/components/DocumentStatus.tsx
- docs/src/content/docs/explanation/color.md
- docs/src/content/docs/reference/color/info-palette.mdx
- docs/src/content/docs/reference/color/success-palette.mdx
Closes #1961 
* Adds success palette reference page
* Adds navigation to new page
> feat(docs): add success palette page & navigation

- packages/panda-preset/package.json
- sandbox/app/globals.css
- sandbox/app/layout.tsx
closes #1971 
Exposes the Pando CSS file in the preset 🙈
> fix: expose the pando.css in the preset

- .github/workflows/docs_release.yml
closes #1981 
Updates action version and settings
> ci: update docs_release.yml

- tsconfig.react.json
closes #1985 
Updates config to use `react-jsx` which is the same setting used by NextJS and Chakra
> chore: update tsconfig.react.json

- docs/src/content/docs/reference/color/action-palette.mdx
- docs/src/content/docs/reference/color/info-palette.mdx
- docs/src/content/docs/reference/color/neutral-palette.mdx
- docs/src/content/docs/reference/color/success-palette.mdx
- docs/src/content/docs/reference/document-status.mdx
#1984 was meant to resolve errors with build so the new docs site can be deployed. [Still seeing some build errors](https://github.com/pluralsight/pando/actions/runs/7477785671/job/20351267090) related to paths.
This updates paths to build successfully.
> fix(docs): update paths for build

- docs/postcss.config.cjs
#1990, #1987, #1984 all attempted to fix build errors for the new docs site. This is related to that effort - the build is [not passing yet](https://github.com/pluralsight/pando/actions/runs/7480132407/job/20358888162).
Adds [the recommended postcss config](https://panda-css.com/docs/installation/astro) from the pandacss docs with astro
> chore: update postcss config

- docs/src/components/ColorSwatch.astro
- docs/src/content/docs/reference/color/action-palette.mdx
- docs/src/content/docs/reference/color/info-palette.mdx
- docs/src/content/docs/reference/color/neutral-palette.mdx
- docs/src/content/docs/reference/color/success-palette.mdx
- docs/src/content/docs/reference/document-status.mdx
#1990, #1987, #1984, #1993, #1994 all attempted to fix build errors for the new docs site. This is related to that effort - the build is [not passing yet](https://github.com/pluralsight/pando/actions/runs/7481397281/job/20362907566).
This modifies all imports to relative to see if the error is path related
> chore: modifying doc imports to relative paths

- docs/src/components/ColorSwatch.astro
- docs/src/content/docs/reference/color/action-palette.mdx
- docs/src/content/docs/reference/color/info-palette.mdx
- docs/src/content/docs/reference/color/neutral-palette.mdx
- docs/src/content/docs/reference/color/success-palette.mdx
- docs/tsconfig.json
closes #1999 
Sets base path to enable absolute path imports in the docs site
> 1999 bug paths

- docs/astro.config.mjs
- docs/src/components/DocumentStatus.tsx
- docs/src/content/docs/explanation/color.md
- docs/src/content/docs/reference/color/warning-palette.mdx
closes #1963
Adds warning palette & associated navigation items
https://github.com/pluralsight/pando/assets/146388897/14a4db85-b02f-4372-a6ab-e32d31a33f84
> feat(docs): Add warning palette reference

- packages/panda-preset/src/recipes/fieldMessage.ts
- packages/panda-preset/src/recipes/index.ts
- packages/react/src/components/Input.tsx
- sandbox/app/components/Nav.tsx
- sandbox/app/react/field-message/page.tsx
- sandbox/app/react/input/page.tsx
- tests/sandbox/pages/fieldMessagePage.test.tsx
closes #1951 
- Adds fieldMessage recipe
> 1951 feature create fieldmessage recipe

- packages/react/panda.config.ts
- packages/react/src/components/TextLink.tsx
- packages/react/src/helpers/textLink.helpers.ts
- packages/react/src/index.ts
- packages/react/tsup.config.ts
- sandbox/app/react/text-link/page.tsx
- tests/react/textLink.test.tsx
- tests/sandbox/pages/textLinkPage.test.tsx
closes #2016 
- Updates TextLink to use recipe
- Relocates tests
- Updates sandbox
- Updates sandbox tests
> 2016 feature refactor textlink component to use textstyle

- packages/design-tokens/package.json
- packages/headless-styles/package.json
- packages/icons/tsconfig.build.json
closes #2022 
- Adds private fields to HS/DT
- Fixes icons tsconfig which is failing due to incompatible settings
> 2022 bug icons package settings breaking publish

- packages/panda-preset/src/recipes/index.ts
- packages/panda-preset/src/recipes/input.ts
- packages/panda-preset/src/recipes/shared/input.base.ts
- packages/panda-preset/src/recipes/textarea.ts
- sandbox/app/components/AppBar.tsx
- sandbox/app/components/Nav.tsx
- sandbox/app/react/textarea/page.tsx
- tests/sandbox/pages/textareaPage.test.tsx
closes #2024 
- Adds `textarea` recipe
- Updates sandbox
- Adds sandbox tests
> 2024 feature create textarea recipe

- packages/panda-preset/src/recipes/checkbox.ts
- packages/panda-preset/src/recipes/index.ts
- packages/panda-preset/src/recipes/shared/input.base.ts
- packages/react/src/components/TextLink.tsx
- sandbox/app/components/Nav.tsx
- sandbox/app/react/checkbox/page.tsx
- sandbox/app/react/text-link/page.tsx
- tests/sandbox/pages/checkboxPage.test.tsx
- tests/sandbox/pages/textLinkPage.test.tsx
closes #2026 
- Adds checkbox slot recipe
- Update sandbox
- Adds sandbox tests
> 2026 feature make checkbox recipe

- .github/workflows/docs_release.yml
[docs deploy with gh action is failing](https://github.com/pluralsight/pando/actions/runs/7576074337)
Modifies `docs_release` script in `.github/workflows` according to [astro docs for gh pages deploy](https://docs.astro.build/en/guides/deploy/github/)
> chore(docs): modify gh workflow for deploy

- packages/react/src/components/Checkbox.tsx
- packages/react/src/index.ts
- packages/react/tsconfig.json
- packages/react/tsup.config.ts
- sandbox/app/react/checkbox/page.tsx
- tests/react/checkbox.test.tsx
- tests/sandbox/pages/checkboxPage.test.tsx
closes #2027 
- Updates Checkbox to use recipe
- Updates sandbox
- Updates tests
> 2027 feature migrate checkbox component to use recipe

- docs/src/components/DocumentStatus.tsx
- docs/src/components/ExampleContent.astro
- docs/src/components/SharedStyles.ts
- docs/src/content/docs/index.mdx
- docs/src/content/docs/reference/color/warning-palette.mdx
- docs/src/content/docs/reference/typography.mdx
Closes #1997
* Migrates remaining typography content from [figma guidelines](https://www.figma.com/proto/uJtPfI38D9i8iQg0UGK2E0/Pando-Design-Guidelines?node-id=533-15987&starting-point-node-id=6%3A11626)
* Merges [typography doc from beta docs](https://design.pluralsight.com/docs/reference/general/typography#font-families) where helpful
https://github.com/pluralsight/pando/assets/146388897/c7bbe677-f7d0-45e5-8c76-70fb7c631c38
> 1997 typography content

- packages/react/src/components/toast.tsx
- packages/react/src/context/Toast/context.tsx
- packages/react/src/context/Toast/types.ts
- packages/react/src/index.ts
- packages/react/tsconfig.json
- packages/react/tsup.config.ts
- sandbox/app/react/toast/page.tsx
- tests/react/context/toastProvider.test.tsx
- tests/react/toast.test.tsx
- tests/sandbox/pages/toastPage.test.tsx
closes #2041 
- Refactors all Toast related components to use recipe
> 2041 feature refactor toast to use recipe r19 compatibility

- packages/react/src/context/Toast/reducer.ts
React lib was missing types
Fixes type error in file that was causing the types to fail
> chore: fix TS error in toast reducer.ts

- scripts/release/build-commands/build-prerelease-packages.mjs
CI release keeps randomly failing to publish
- Kills unused artifact copy on the CI job since we no longer store artifacts.
> ci: remove unused artifact copy

- scripts/release/build-commands/build-prerelease-packages.mjs
ci prepare job failing from outdated script
Updates command to use current `build` script
> chore: update build-release-packages.mjs

- packages/panda-preset/package.json
- packages/panda-preset/root.css
> fix(preset): allow root.css to be exported

- packages/react/package.json
package breaking from exports using a non-relative path
Literally...adds a period. 🙈
> chore: add period to icons path

- docs/package.json
Troubleshooting [build issues](https://github.com/pluralsight/pando/actions/runs/7674219108/job/20918388584) related to pnpm and docs
> chore: use pnpm for docs build

- .github/workflows/docs_build.yml
- .github/workflows/docs_release.yml
- docs/package.json
troubleshooting [docs build and deploy failures](https://github.com/pluralsight/pando/actions/runs/7674219108/job/20918388584)
> chore: docs codegen script

- .github/workflows/docs_release.yml
[v1 docs release failing](https://github.com/pluralsight/pando/actions/runs/7674509582) - reverting package manager to bun to see if that changes outcome.
> chore: revert astro deploy pm to bun

- docs/astro.config.mjs
- docs/src/components/DocumentStatus.tsx
- docs/src/content/docs/explanation/faq.mdx
- docs/src/content/docs/explanation/versioning-policy.md
- docs/src/content/docs/tutorials/add-pando-to-a-website.md
- docs/src/content/docs/tutorials/migrating-from-classic-psds.md
closes #2070
Adds FAQ explanation page as well as supporting docs pages (as placeholders)
https://github.com/pluralsight/pando/assets/146388897/501e41c1-7a9d-41d1-8148-cbee88d7ed0f
> feat(docs): add faq

- docs/src/components/DocumentStatus.tsx
- docs/src/content/docs/explanation/faq.mdx
- docs/src/content/docs/explanation/versioning-policy.md
- docs/src/content/docs/explanation/versioning-policy.mdx
- docs/src/content/docs/tutorials/add-pando-to-a-website.md
- docs/src/content/docs/tutorials/migrating-from-classic-psds.md
Closes #2081
Migrates `versioning policy` from [the beta docs](https://design.pluralsight.com/docs/learn/about-pando/versioning). Edits & modifies wording where it felt beneficial 👍  
https://github.com/pluralsight/pando/assets/146388897/2e13b314-2af7-4d53-8424-e0edac1a7917
> feat(docs): migrate versioning policy

- .github/workflows/publish_experimental_release.yml
- .github/workflows/publish_next_release.yml
- packages/pando/package.json
- scripts/release/build-commands/build-prerelease-packages.mjs
closes #2091 
- Updates release scripts to build icons first then all dependent packages
> ci: test experimental build fix

- packages/panda-preset/src/recipes/admonition.ts
- packages/panda-preset/src/recipes/index.ts
- packages/panda-preset/src/recipes/shared/admonition.base.ts
- sandbox/app/components/Nav.tsx
- sandbox/app/react/admonition/page.tsx
- tests/sandbox/pages/admonitionPage.test.tsx
closes #2048 
Adds the admonition recipe
> 2048 feature make admonition recipe

- packages/panda-preset/src/recipes/shared/button.base.ts
- packages/react/src/context/Toast/context.tsx
- packages/react/src/context/Toast/types.ts
closes #2120 
- Adds new `mount` option to `show`
- Updates Buttons to use token (still will be temporarily broken in light mode)
> 2120 feature add rootid to toast helper

- packages/react/src/components/toast.tsx
closes #2122 
Uses inline style functions that work in other components due to Reacts inability to render performantly (just keeping it real).
> fix(react): update toast.tsx to use inline functions

- docs/astro.config.mjs
- docs/src/content/docs/reference/available-in-v1.mdx
closes #2124
Adds doc to track status & availability of v1 components, hooks, and helpers
https://github.com/pluralsight/pando/assets/146388897/169aeba1-859c-4144-a4a9-19b15eab16ef
> feat(docs): available in v1

- docs/src/components/ReactLib/ThemeSelect.astro
Introduces top level `<ViewTransitions />` on docs site which is referred to as "SPA mode" in the [Astro docs](https://docs.astro.build/en/guides/view-transitions/)
smoother transition from page to page + prevents the FOUC (flash of unexpected content) that has been associated with navigating in light & dark mode
https://github.com/pluralsight/pando/assets/146388897/a57b932f-7c91-4abc-bb8a-5142984b79cf
> feat(docs): enable SPA mode for docs site

- packages/react/src/context/Toast/context.tsx
closes #2128 
Updates Toast context to use Match pattern to provide static palette props
> refactor(react): update toast context to use Match pattern

- .github/dependabot.yml
Dependabot looks at sandbox & docs daily
Dependabot looks at sandbox & docs weekly for dependency upgrades
> chore: dependabot frequency for sandbox and docs

- packages/panda-preset/src/recipes/index.ts
- packages/panda-preset/src/recipes/radio.ts
- packages/panda-preset/tsconfig.lint.json
- sandbox/app/components/Nav.tsx
- sandbox/app/react/radio/page.tsx
- tests/sandbox/pages/radioPage.test.tsx
closes #2141 
Adds radio recipe
> feat: add radio recipe

- docs/package.json
- docs/src/components/ReactLib/TextLink/TextLink.astro
- pnpm-lock.yaml
Closes #2139 
External links will have `target="_blank"` to open a new tab and internal links will still navigate within the app.
https://github.com/pluralsight/pando/assets/146388897/711ab298-3096-488a-96e1-ff1e7ec67510
> feat(docs): external link opens new tab

- docs/src/content/docs/reference/available-in-v1.mdx
`Available in v1` lists radio as "coming soon"
Changes status to available and adds link to sandbox
> chore: update available in v1 to reflect radio

- docs/src/components/ComponentNav.astro
- docs/src/content/docs/reference/components/button/guidelines.mdx
- docs/src/content/docs/reference/components/button/implementation.mdx
- docs/src/content/docs/reference/components/button/overview.mdx
- docs/src/content/docs/reference/components/button/usage.mdx
Closes #2158
Creates local nav for button reference doc
https://github.com/pluralsight/pando/assets/146388897/1f16ab59-aa0f-49b6-afc8-cdc7ffe8ad4c
> 2158 docs nav

- docs/src/content/docs/reference/components/button/implementation.mdx
closes #2156
Adds content for button implementation page
https://github.com/pluralsight/pando/assets/146388897/5a905183-4a34-43a3-a608-0de537ff5493
> feat(docs): content for implementation page

- packages/panda-preset/src/recipes/index.ts
- packages/panda-preset/src/recipes/skeleton.ts
- sandbox/app/components/Nav.tsx
- sandbox/app/react/skeleton/page.tsx
closes #2143 
- Adds skeleton recipe
> 2143 feature create skeleton recipe

- packages/panda-preset/src/recipes/badge.ts
- packages/panda-preset/src/recipes/index.ts
- packages/panda-preset/src/recipes/shared/badge.base.ts
- sandbox/app/components/Nav.tsx
- sandbox/app/react/badge/page.tsx
- tests/sandbox/Nav.test.tsx
- tests/sandbox/pages/badgePage.test.tsx
closes #2172 
Adds badge recipe
> 2172 feature add badge recipe

- docs/src/content/docs/reference/available-in-v1.mdx
Skeleton was showing in "coming soon" in v1 availability
Skeleton is moved to "available" with link to sandbox
> chore: update skeleton availability

- docs/src/content/docs/reference/available-in-v1.mdx
available in v1 page has badge in "coming soon"
Moves badge to "available" with link to sandbox
> chore: update availability for badge

- packages/panda-preset/src/recipes/index.ts
- packages/panda-preset/src/recipes/tag.ts
- sandbox/app/components/Nav.tsx
- sandbox/app/react/tag/page.tsx
- tests/sandbox/pages/tagPage.test.tsx
> feat: add tag recipe

- docs/src/content/docs/reference/available-in-v1.mdx
Tag component is showing as coming soon 
Tag & Link to sandbox are in the available table
> chore: update tag availability in docs

- docs/astro.config.mjs
- docs/src/components/DoDontHeaders.tsx
- docs/src/components/DocumentStatus.tsx
- docs/src/components/LiveCodeExamples/Button/LiveButton.tsx
- docs/src/components/LiveCodeExamples/Button/LiveButtonEditor.astro
- docs/src/components/LiveCodeExamples/Button/LiveButtonExamples.ts
- docs/src/components/LiveCodeExamples/Form/LiveForm.tsx
- docs/src/components/LiveCodeExamples/Form/LiveFormEditor.astro
- docs/src/components/LiveCodeExamples/IconButton/LiveIconButton.tsx
- docs/src/components/LiveCodeExamples/IconButton/LiveIconButtonEditor.astro
- docs/src/content/docs/reference/components/button/guidelines.mdx
- docs/src/content/docs/reference/components/button/implementation.mdx
- docs/src/content/docs/reference/components/button/overview.mdx
- docs/src/content/docs/reference/components/button/usage.mdx
- docs/src/content/docs/reference/components/icon-button/guidelines.mdx
- docs/src/content/docs/reference/components/icon-button/implementation.mdx
- docs/src/content/docs/reference/components/icon-button/overview.mdx
- docs/src/content/docs/reference/components/icon-button/usage.mdx
- docs/src/content/docs/reference/components/text-link/guidelines.mdx
- docs/src/content/docs/reference/components/text-link/implementation.mdx
- docs/src/content/docs/reference/components/text-link/overview.mdx
- docs/src/content/docs/reference/components/text-link/usage.mdx
- docs/src/styles/overrides.css
closes #2157
Adds content to Button guidelines page
See [Figma Plan](https://www.figma.com/file/QCCfhqzVd2HHRuqc2GBbGq/Component-page?type=whiteboard&node-id=2-47&t=u5adyUtlzdCeBQlR-0) as reference for content
https://github.com/pluralsight/pando/assets/146388897/83b80ccd-d76a-4a47-8e96-60efdbf7f4e5
> 2157 feat button guidelines

- docs/package.json
- pnpm-lock.yaml
updates docs site to most recent next version of `@pluralsight/react` and `@pluralsight/panda-preset`
> chore(docs): update next package versions for pando packages

- docs/astro.config.mjs
- docs/src/components/LiveCodeExamples/Button/LiveButton.tsx
- docs/src/components/LiveCodeExamples/Zindex/LiveZIndex.tsx
- docs/src/components/LiveCodeExamples/Zindex/ZIndexEditor.astro
- docs/src/content/docs/reference/z-index.mdx
closes #2190
Includes z-index doc in reference section
https://github.com/pluralsight/pando/assets/146388897/06adc648-1b68-4f14-82d1-fda6d1a552d3
> feat(docs): include z-index value reference

- packages/panda-preset/src/recipes/index.ts
- packages/panda-preset/src/recipes/progress.ts
- sandbox/app/components/Nav.tsx
- sandbox/app/react/progress-bar/page.tsx
- tests/sandbox/pages/progressBar.test.tsx
closes #2191 
Adds progress recipe
> feat: add progress recipe

- docs/astro.config.mjs
- docs/src/components/ReactLib/ThemeSelect/ThemeSelectButton.tsx
- docs/src/components/SocialIcons.astro
closes #2196
moves external links in the left side nav to the top social icon area
* Replaces the native astro `SocialIcons.astro` component because it restricts icons usage to those offered by starlight
* removes the youtube link from social icons as it is not regularly updated currently
* replaces the light/dark switch emoji's to icons for accessibility purposes
https://github.com/pluralsight/pando/assets/146388897/548c0c99-3e63-4117-9534-4b9b18f70417
> 2196 nav links

- docs/src/content/docs/reference/available-in-v1.mdx
Progress Bar shows as "coming soon" in v1 availability doc
Moves Progress bar to available table with link to sandbox
> chore(docs): update progress bar v1 availability

- docs/src/content/docs/tutorials/add-pando-to-a-website/step-3.mdx
in the install pando tutorial step 3, `data-color-mode` and `data-theme` are set in a div rather than html tag
* changes to html tag for better example
* adds a little bit of margin to the bottom of `See how we use useTheme in our sandbox`
> Update div to html

- packages/panda-preset/src/conditions.ts
- packages/panda-preset/src/recipes/index.ts
- packages/panda-preset/src/recipes/switch.ts
- packages/panda-preset/src/recipes/textLink.ts
- sandbox/app/components/Nav.tsx
- sandbox/app/react/switch-input/page.tsx
- tests/panda-preset/conditions.test.ts
- tests/sandbox/pages/switchInputPage.test.tsx
closes #2208 
- Adds `switchInput` recipe
- Adds new conditions for easier switch selection
> 2208 feature make switch recipe

- packages/react/src/components/Toggle.tsx
- packages/react/src/context/FormControl.tsx
- packages/react/src/index.ts
- packages/react/tsconfig.json
- packages/react/tsconfig.lint.json
- packages/react/tsup.config.ts
- sandbox/app/react/switch-input/page.tsx
- tests/react/switch-input.test.tsx
closes #2209 
Exposes SwitchInput components
> 2209 feature refactor switch to use recipe

- docs/src/content/docs/reference/available-in-v1.mdx
Switch Input shows as "coming soon" on v1 availability docs
* Includes in "available in v1" table with link to sandbox
* alphabetizes available v1 components
> docs: update switch input availability doc

- docs/package.json
- docs/tsconfig.json
- package.json
- pnpm-lock.yaml
docs was using the workspace `@pluralsight/icons` version
docs imports the deployed `@pluralsight/icons` version to match other pando packages
> chore: reference deployed pando/icon pkg

- packages/panda-preset/src/recipes/button.ts
- packages/panda-preset/src/recipes/iconButton.ts
- packages/panda-preset/src/recipes/shared/button.base.ts
- packages/react/src/components/IconButton.tsx
- sandbox/app/react/icon-button/page.tsx
closes #2180 
Adds "outline" usage to iconbutton
> feat: add sandbox outline usage

- docs/src/content/docs/reference/available-in-v1.mdx
v1 availability list does not include modal
Modal work will be included in AlertDialog, so it includes it there
> docs: update list to include modal

- docs/astro.config.mjs
- docs/package.json
- docs/src/components/DocumentStatus.tsx
- docs/src/components/LiveCodeExamples/CircularProgress/LiveCircularProgress.tsx
- docs/src/components/LiveCodeExamples/CircularProgress/LiveCircularProgressEditor.astro
- docs/src/components/LiveCodeExamples/CircularProgress/LiveCircularProgressExamples.ts
- docs/src/content/docs/reference/available-in-v1.mdx
- docs/src/content/docs/reference/components/circular-progress/code.mdx
- docs/src/content/docs/reference/components/circular-progress/guidelines.mdx
- docs/src/content/docs/reference/components/circular-progress/overview.mdx
- docs/src/content/docs/reference/components/circular-progress/usage.mdx
- docs/src/styles/tooltip.css
- packages/panda-preset/src/recipes/circularProgress.ts
- packages/react/src/components/CircularProgress.tsx
- packages/react/src/helpers/circularProgress.helpers.ts
- pnpm-lock.yaml
- sandbox/app/react/circular-progress/page.tsx
Closes [PDS-84](https://pluralsight.atlassian.net/jira/software/c/projects/PDS/issues/PDS-84)
- Adds docs pages for CircularProgress
- Populates content for CircularProgress Overview page
- Modifies recipe for CircularProgress to match design guidelines language & colors - base & progress colors were swapped
https://github.com/pluralsight/pando/assets/146388897/ae205bca-30cb-4eb0-8c51-810041eca17b
> Pds 84 circularprogress overview

- docs/package.json
- pnpm-lock.yaml
update pando docs to latest pando next release
> chore: update pando packages in docs

- docs/package.json
- pnpm-lock.yaml
update pando package next version in docs
> chore: update pando in docs site

- docs/README.md
- sandbox/README.md
Adds helpful content to the docs and sandbox README's
> Sandbox docs readmes

- README.md
- docs/README.md
- packages/panda-preset/README.md
- packages/react/README.md
- sandbox/README.md
- sandbox/app/components/AppBar.tsx
Updates README's with additional helpful information
> docs: update READMEs based on feedback
